

   ____________________
   (BUTTON)

Meaning of "alam"

alam •

   n.
     *
          + knowledge

   adj.
     *
          + maalam (ma-) knowledgeable, well-versed

» synonyms and related words:

   tell
   v.
     *
          + 1. to put in words, say: magsabi, sabihin
          + 2. to inform, tell to: magpatalastas, ipatalastas,
            pagpatalastasan, magpabatid, ipabatid, sabihin, sabihan
          + 3. to make known: magbigay-alam, ipagbigayalam, ipaalam
          + 4. to know, inform: malaman, mabatid
          + 5. to order, command: mag-utos, iutos, utusan, mag-atas,
            iatas, atasan
          + 6. to count, count one by one: magbilang, bumilang, bilangin
          + 7. to tell a lie: magsinungaling, magsinungaling,
            pagsinungalingan, magbulaan, pagbulaanan
          + 8. to tell the truth: magtapat, ipagtapat, pagtapatan, sabihin
            ang katotohanan
          + 9. to tell a story: magkuwento, ikuwento, magbida, ibida
          + 10. to tell on somebody: magsumbong, ipagsumbong, isumbong

   wisdom
   n.
     *
          + 1. being wise: dunong, karunungan
          + 2. knowledge and good judgement based on experience: alam,
            kaalaman, kaalaman, talino, katalinuhan
          + 3. wise conduct, wise words: kaalaman, karunungan, katalinuhan

   inform
   v.
     *
          + 1. to supply with knowledge: ipaalam, magpabatid, pabatiran,
            ipabatid
          + 2. to tell: magsabi, sabihin
          + 3. to give notice of: magpatalastas, ipatalastas, magpabatid
          + 4. to acquaint with a fact: magbigay-alam, ipagbigay-alam

   name
   n.
     *
          + 1. a word or words by which a person, animal, place or thing
            is spoken of or to: pangalan, ngalan
          + 2. a word that means any object, or any one of a group of
            objects: tawag, katawagan
          + 3. reputation: puri, karangalan, mabuting pangalan
          + 4. title: pamagat, titulo

   v.
     *
          + 1. to give a name to: magngalan, ngalanan, pangalanan,
            ingalan, ipangalan
          + 2. to mention by name: sabihin ang pangalan
          + 3. to give or know the right name for: alam ang pangalan ng o
            ang tawag sa
          + 4. to mention, give as an instance, cite: bumanggit,
            banggitin, tumukoy, tukuyin

   notice
   n.
     *
          + 1. heed, attention: pansin
          + 2. a warning: babala
          + 3. a written or printed sign: paunawa, patalastas, pabatid
          + 4. telling that one is leaving a persons employ: paunang-sabi
          + 5. a written or printed account in a newspaper: balita,
            pahayag, paunawa, patalastas

   v.
     *
          + 1. to give attention to, see: pumansin, mapansin, pansinin,
            pumuna, mapuna, punahin, umino, maino, inuhin
          + 2. to give notice that one will leave ones employ, etc.:
            magbigay-alam or magsabi

   sensible
   adj.
     *
          + 1. having good sense, showing good judgment, wise: makatwiran,
            may katwiran, may sentido komun, marunong, matalino, matino
          + 2. aware, conscious: alam, nalalaman, nadarama, batid,
            nababatid
          + 3. that can be noticed: mapapansin, kapansin-pansin, nakikita,
            halatain, kapuna-puna

   communication
   n.
     *
          + giving information: pagpapahatid ng balita, pagbabalita,
            pagbibigay-alam, pagpapatalastas

   public
   adj.
     *
          + 1. of the people: ng madla, ng publiko
          + 2. belonging to the people: pambayan, ng bayan
          + 3. for the people, serving the people: panlahat,
            pangkalahatan, pangmadla, pambayan, pangmamamayan
          + 4. known to many or all: hayag, kalat, alam ng lahat

   n.
     *
          + 1. all the people: mga tao, taong-bayan, madla, masa
          + 2. in public, publicly, openly, not in private or secretly:
            hayagan, lantaran

   set
   v.
     *
          + 1. to put in some place, put, place: maglagay, ilagay, lagyan
          + 2. to arrange, put in proper order: mag-ayos, ayusin, iayos,
            isaayos, maghanda, ihanda, mag-areglo, aregluhin
          + 3. to become fixed, become firm or hard: tumigas, manigas,
            maging matigas, mabuo, mamuo
          + 4. to go down, sink: lumubog
          + 5. to begin to move, start: magsimula, simulan, mag-umpisa,
            umpisahan
          + 6. to fix: magtakda, itakda

   adj.
     *
          + that has been set, fixed, arranged, formal: nakatakda,
            nakahanda, inihanda

   n.
     *
          + 1. group, things or people belonging together: pulutong,
            pangkat, magkakasama, huwego
          + 2. to set about, to begin, start work: magsimula, simulan,
            pasimulan, mag-umpisa, umpisahan
          + 3. to set aside, to put to one side: magbukod, ibukod,
            maghiwalay, ihiwalay
          + 4. to put by for later use: magtabi, itabi, magtago, itago,
            magbukod, ibukod
          + 5. to set down, to put down, deposit or let alight: ibaba,
            ilagay
          + 6. to set forth, to make known, express, declare:
            magbigay-alam, ipagbigayalam, magpahayag, ipahayag
          + 7. to start to go: umalis na patungo
          + 8. to set off, to cause to explode: magpaputok, paputukin,
            magpasambulat, magpasabog, pasabugin
          + 9. to set out, to start to go: umalis
          + 10. to spread out to show, sell, or use: magkalat, ikalat
          + 11. to set to, to begin: magsimula, simulan, mag-umpisa,
            umpisahan

   understood
   adj.
     *
          + known: alam, nalalaman, batid, nababatid, talastas,
            natatalastas

   out
   adj.
     *
          + 1. not at home, away from office, work, etc.: wala (sa bahay,
            opisina, atb.), nasa labas
          + 2. not burning, not lighted: patay
          + 3. not correct: mali, sala
          + 4. made known, e.g. a secret: hayag na, alam na
          + 5. into the open so as to be seen: litaw adv. 1. forth:
            palabas, papalabas
          + 2. aloud, plainly: malakas, maliwanag
          + 3. out of, not within: wala, nasa labas
          + 4. beyond the reach of: napakalayo, di maabot
          + 5. without: wala
          + 6. because of: dahil sa
          + 7. from: sa, mula sa

   know
   v.
     *
          + 1. to know: alam
          + 2. to know someone: makilala, kilalanin
          + 3. to have knowledge of: malaman, mabatid
          + 4. to understand: umunawa, maunawaan
          + 5. to learn: matuto, matutuhan
          + 6. to let know: ipaalam, ipabatid, sabihin, pagsabihan,
            ibalita, balitaan

   adj.
     *
          + to be thoroughly familiar with: marunong, maalam

   aywan
   phrase.
     *
          + be ignorant of something. Aywan ko. I don't know. [var. ewan]
            [syn. di alam]

   ha
   int.
     *
          + interrogative meaning: What is it?, What do you mean?, What's
            that again? [syn. ano?, ano kamo?] part. interrogative
            particle meaning: Do you understand? [syn. Alam mo na ba, ha?]
            part. exclamatory interrogative particle with the element of
            surprise or reproach: Is that so? [syn. Ganoon pala, ha? So
            that's what it is, huh?]
          + 2.) ha! intj. (deprecatingly) So!, (reproachingly) So, that's
            it!, particle producing laughter (in series) Ha! Ha! Ha!

   paalam
   intj.
     *
          + farewell (from alam)

   v.
     *
          + magpaalam (mag-) to bid goodbye. Magpaalam ka sa iyong ina.
            Say goodbye to your mother.


