

ABAY

   pronounced AH-bahy

   Sinong abay mo?
   Who’s your _______ ?

   abay
   escort

   abay
   consort

   abay
   bridesmaid

   abay
   maid of honor

   abay
   best man
     __________________________________________________________________

MGA KAHULUGAN SA TAGALOG

   abay: pareha, hatid, konsorte, katambal, kumboy

   abay: dama, tagahatid sa isang ikakasal

   abay: siping, dait, tabi, dais
