

   ____________________

Meaning of "agaw"

agaw •

   n.
     *
          + sudden snatching away

   v.
     *
          + mang-agaw, agawin, agawan (mang-:-in:-an) to snatch, to grab.
            Nang-agaw siya ng bag. He snatched (somebody's) bag. umagaw
            (um-)

   v.
     *
          + to participate in grabbing. Umagaw ka sa pabitin. (Get in
            there and) grab the hanging object.


