

AGOS

   agos
   flow (of water) Takbo o galaw ng tubig at iba pang likido.

   agos ng buhay
   flow of life

   agos ng dugo
   blood flow

   agos ng tubig
   waterflow

   malakas na agos ng tubig
   strong flow of water

   Mabilis ang agos ng tubig.
   The water is flowing fast.
     __________________________________________________________________

   umagos
   flowed

   umaagos
   is flowing
