

AKIBAT

   akibat: carrying over the shoulder and across the body

   kaakibat: associate, associated with

   Kaakibat sa kanilang pag-alis ang panghihina ng kanilang mga magulang.
   Along with their departure was the weakening of their parents.

   Kaakibat nito ang paggamit sa sariling wika.
   With this is the usage of one’s own language.

KAHULUGAN SA TAGALOG

   akibat: suot o taglay bilang dalang sagisag, emblema, simbolo
