

AKLAS

   welga, istraik, aklásan

   ak·lás
   revolt

   Manahimik o Mag-Aklas
   Stay Silent or Revolt

   Pag-Aklas ng Mga Manggagawa
   Workers’ Strike

   The Filipino word for a laborers’ strike is welga from the Spanish
   huelga.

KAHULUGAN SA TAGALOG

   aklás: organisadong pagtanggi ng mga obrero na magtrabaho hanggang
   mabigyan ng lunas ang kanilang karaingan

   aklasín, iaklás, mag-aklás.
