

ALAHAS

   This is from the Spanish plural word alhajas.

   alahas
   jewels, jewelry

   Ang dami mong alahas!
   You’ve got a lot of jewelry!

   Itago mo ang mga alahas mo.
   Hide your jewelry.
     __________________________________________________________________

   alahasan
   jewelry store

   kuwintas at pulseras
   necklace and bracelet

   mga hikaw at singsing
   earrings and rings
