

   ____________________

Meaning of "alamat"

alamat •

   n.
     *
          + folklore, tradition

» synonyms and related words:

   fable
   n.
     *
          + 1. a story that is made up to teach a lesson: pabula,
            kuwentong nagbibigay-aral
          + 2. a fictitious narrative or statement: katha-katha, gawa-gawa
          + 3. a legend: alamat

   legend
   n.
     *
          + a story coming down from the past, which many people have
            believed: alamat


