

ALIKABOK

   sometimes simply as abok, though not so common

   alikabok
   dust

   makapal na alikabok
   thick dust

   Makapal ang alikabok.
   The dust is thick.

   naalikabukan
   to have gathered dust
   Hindi ginagamit kaya inalikabukan.
   Wasn’t being used so it just gathered dust.

   maalikabok
   dusty (place, location)

   maalikabok na daan
   dusty road

   inalikabukang mesa
   dusty table (a table on which dust has gathered)
