

ANGKÁN

   ang·kán

   angkán
   family, clan

   kaangkan
   of the same family clan

   ang kanilang angkan
   their tribe

   talaangkanan
   family tree

   talaangkanan
   list of descendants

   Mula sa mayamang angkan ang ating panauhing pandangal.
   Our guest of honor is from a rich clan.

MGA KAHULUGAN SA TAGALOG

   angkán: pinagmulang pamilya

   angkán: mga tao na may nagkakaisang pinagmulang henetiko at henealohiya
