

ANTÍNG-ANTÍNG

   an·tíng-an·tíng

   antíng-antíng
   magical powers
   May anting-anting ang bata.
   The child has special powers.

   Ex-president Ferdinand Marcos supposedly was given the power to become
   invisible by Gregorio Aglipay.

   This is distinct from agimat, which is a physical object.

KAHULUGAN SA TAGALOG

   antíng-antíng: bagay na pinaniniwalaang may kapangyarihang magligtas sa
   nagmamay-ari laban sa anumang kapahamakan
