

APO

   This is a gender-neutral word.
   apó
   grandchild

   apó
   grandson /
   granddaughter

   mga apó
   grandchildren

   ang aking apó
   = ang apó ko
   my grandchild

   ang aking mga apó
   = ang mga apó ko
   my grandchildren
     __________________________________________________________________

   apo sa tuhod
   great-grandchild

   apo sa talampakan
   great-great-grandchild

   apo sa kalingkingan
   great-great-great-grandchild
