

ARI

   propyedad, biyenes

   arì
   property

   arí-arian
   possessions, property, goods
     __________________________________________________________________

   may-arì
   owner

   Sino ang may-arì?
   Who’s the owner?
     __________________________________________________________________

   ariin
   to consider, acknowledge

   paarî
   possessive

   pag-aarì
   property

   pagka-may-arì
   ownership, possession

   karapatang-ari
   copyright
