

ATIN

   This is a pronoun.
   atin
   our, ours
   (including the person being spoken to)

   amin
   our, ours
   (not including the person being spoken to)

   Atin ito.
   This belongs to us. (you and us)

   Amin ito.
   This belongs to us. (but not you)

   ang ating bansa
   our country

   Alin ang atin?
   Which is ours?

   Atin ba ito?
   Is this ours?

   Huwag kunin ang di atin.
   Don’t get what’s not ours.

   Ating gamitin ang ilaw.
   Let’s use the light.
