

ATUBILI

   atubilí
   hesitation

   atubili
   reluctance

   mag-atubili
   to hesitate, waver

   mag-atubili
   to be reluctant

   Huwag kang mag-atubili.
   Don’t hesitate (to ask for help).

   Huwag kang mag-atubiling humingi ng tulong.
   Don’t hesitate to ask for help.

MGA KAHULUGAN SA TAGALOG

   atubilî: may alinlangan

   atubilî: bantulót

   natitigilan, nag-aalanganin, nag-uulik-ulik, bantulot, urung-sulong
