

AYOS

   kaayusan, pagkamaayos; areglo, hanay, salansan; kalagayan, katayuan,
   anyo, kaanyuan; sitwasyon, kondisyon
   áyos
   order, arrangement

   Ayos!
   Good! OK!

   Ayos lang.
   Just fine.

   Ayos na.
   Fixed already.
   = Good already.

   maayos
   orderly

   Ayusin mo ito.
   Put this in order.
   = Fix this.

   Inayos ko ang radyo.
   I fixed the radio.

   isinaayos, isinasaayos
