

BA

   The Tagalog word ba is used in properly forming questions.

   Kumain ka?
   You ate?

   Kumain ka ba?
   Did you eat?
     __________________________________________________________________

   Pilipino ka?
   You’re Filipino?

   Pilipino ka ba?
   Are you Filipino?
     __________________________________________________________________

   Bakit?
   Why?

   Bakit ba?
   And why is that?
   (rough translation; the meaning
   would depend on the context)
     __________________________________________________________________

   Masaya ka?
   You’re happy?

   Masaya ka ba?
   Are you happy?
     __________________________________________________________________

   Miss mo ako?
   You miss me?

   Na-miss mo ba ako?
   Did you miss me?
     __________________________________________________________________

   Bababa ka ba?
   Are you going down? (elevator)

   Bababa ka ba?
   Are you getting off? (vehicle)
     __________________________________________________________________

   Another form of this word: bang

   Meron kang pera?
   You have money?

   Meron ka bang pera?
   Do you have money?
     __________________________________________________________________

   Anong kinain mo?
   What did you eat?

   Ano bang kinain mo?
   So what was it that you ate?
   (asking for additional information after another statement had been
   given; for example, if someone had said she had a stomachache)
