

BAHAGYA

   katiting, kaunti, para bagang, parang (tila) hindi

   bahagyâ
   slightly, a little, somewhat

   Bahagyâ lamang ang lagnat.
   The fever is merely slight.

   Nasaktan ako nang bahagyâ.
   I was slightly hurt.

   Bawasan nang bahagyâ ang tubig.
   Reduce the water slightly.

   Bumaba nang bahagyâ and presyo.
   The price declined slightly.
     __________________________________________________________________

   Related Tagalog words: medyo, kaunti
