

   ____________________

Meaning of "balsa"

balsa •

   n.
     *
          + raft

» synonyms and related words:

   float
   v.
     *
          + 1. to stay on top of water: lumutang
          + 2. to make a thing stay on top of water: magpalutang,
            palutangin

   n.
     *
          + 1. an artistic float used in parades: karosa
          + 2. a raft: balsa
          + 3. anything that stays up or holds up something else in water:
            palutang


