

   ____________________

Meaning of "bangon"

bangon •

   n.
     *
          + rising from a lying position

   v.
     *
          + bumangon (-um-) to rise from a lying position, to get up from
            bed. Bumangon siya nang maaga kanina. He got up early a while
            ago. magbangon, ibangon (mag-:i-)

   v.
     *
          + to raise something, to see something in an upright position.
            Ibangon mo ang may sakit. Help the sick person get up.


