

BANSA

   nasyon, lupang tinubuan, inang-bayan
   bansâ
   nation, state, country

   sa bansang Tsina
   in the country of China

   bansang sinilangan
   country where one was born

   pambansâ
   national

   tulad ng ibang mauunlad na bansa sa daigdig
   like other developed nations of the world

   Inglatera
   England
     __________________________________________________________________

MGA KAHULUGAN SA TAGALOG

   bansâ: komunidad ng mga mamamayan na may iisang lahi, kasaysayan, wika,
   kultura, at pamahalaan

   bansâ: teritoryo ng komunidad na ito
