

BARKO

   This word is from the Spanish barco.
   barkó, n
   ship

   mga barkó
   ships

   Ang barkó ay nawala sa dagat.
   The ship disappeared in the ocean.

   barkong kulay puti
   a ship colored white

   Lumubog ang barkó.
   The ship sank.

   Sumakay kami ng barkó.
   We rode on a ship.

   Malaki ang barkong ito.
   This ship is big.

   Another Tagalog word for ‘ship’ is bapor, which originally referred to
   steamships.

   The Tagalog word for ‘boat’ is bangka.
