

BATIKOS

   batikos: hit with a cudgel

   batikos: criticism

   batikusin: to hit with a cudgel

   batikusin: criticize

   pambatikos: cudgel

KAHULUGAN SA TAGALOG

   batikos: hagupit, palo, tuligsa, atake

   batikos: kritika

   batikos: upasala, mura, alimura

   bumatikos, binatikos, pambabatikos

   Sa pagbatikos nina Bonifacio at Jacinto sa kolonyalismong Kastila,
   mapapansing tila nakapaloob pa rin sila sa diskursong Kristyano.
