

BAYBAY

   mamamaybay
   baybay
   edge, border, coast

   baybayin
   to enumerate

   baybay
   spelling

   palabaybayan
   spelling

   mga maling baybay
   wrong spellings
     __________________________________________________________________

   These days, the root word baybay is more associated with spelling.

   Kung ano ang bigkas, iyon ang baybay.
   The spelling is the way you pronounce it.

   mga salitang pareho ang baybay pero magkaiba ang kahulugan
   words with the same spelling but different meanings

   Mga halimbawa ng mga salitang pareho ang baybay pero magkaiba ang ibig
   sabihin
   Examples of words with the same spelling but are different in meaning
   (homonyms)

   Mga Salitang Magkapareho ang Baybay Ngunit Magkaiba ang Diin
     __________________________________________________________________

MGA KAHULUGAN SA TAGALOG

   baybáy: lupa sa gilid ng dagat

   pagbaybáy: wastong pagsunod-sunod ng mga titik sa pagbuo ng mga salita

   baybáyin: tawag sa sinaunang alpabeto ng mga Filipino

   baybáyin: kabuuan ng lahat ng titik ng isang wika.
     __________________________________________________________________

   Baybayin is an ancient script used in the Philippines before the
   arrival of the Spaniards.
