

BIBIG

   bahagi ng katawan na kinalalagyan ng dila at ngipin
   bibig
   mouth

   Ibuka mo nang malaki ang iyong bibig.
   Open your mouth wide.
     __________________________________________________________________

   mabibig
   talkative

   magbibig-anghel
   to be “angel mouth”
   – all one says comes true

   A coarser Tagalog word for ‘mouth’ is bunganga.

   The term for ‘lips’ is mga labi.
