

BIGÁT

   timbang; sobrang [66]timbang; (patalinhaga) kalubhaan, katindihan,
   grabedad; halaga, kahalagahan, importansya
   bigát
   heaviness, weight

   Ang bigát mo!
   You’re so heavy!

   bumigát
   became heavy

   mabigát
   heavy

   Wow, pare, bigát.
   (slang expression)
   Wow, dude, that’s heavy.
   = That’s deep.

   Ang kasalungat ng salitang bigát ay gaan.
   The opposite of the word heaviness is lightness.
