

   ____________________

Meaning of "bilasa"

bilasa •

   adj.
     *
          + stale, not fresh

» synonyms and related words:

   stale
   adj.
     *
          + 1. not fresh: luma, dati, laon
          + 2. referring to fish: bilasa
          + 3. for food that has become sour or spoiled: sira, panis
          + 4. for food, wine, etc., that has lost its good taste: lipas,
            wala nang lasa


