

BILIS

   tulin, liksi, dalas
   bilis
   speed

   kabilisan
   quickness, celerity

   mabilis
   fast, quick

   Gaano kabilis ito?
   How fast is this?

   Bilisan mo.
   Hurry up.

   [66]Paki-bilis… Pakibilisan…
   Please hurry…

   Bilis-bilisan n’yo nga.
   Hurry up, will you all?

   Bilisan ninyong lahat.
   Hurry up, all of you.

   Ang bilis mo!
   You’re so fast.

   Ang kasalungat ng salitang bilis ay bagal.
   The opposite of the word speed is slowness.
