

BILOG

   sirkulo; parang bola, hugis-lobo, paikot, paikit

   bilóg
   round

   bilóg na buwan
   round moon

   Ang buwan ay bilóg.
   The moon is round.

    Bilóg ang buwan.
   The moon is round.
     __________________________________________________________________

   hating-bilog
   semi-circle

   dobleng bilog
   double circle

   dalawang malaking bilog
   two large circles

   Bilugan mo ang tamang sagot.
   Circle the right answer.

   habilog
   oval

   Ang kasalungat ng salitang bilog ay kuwadrado.
   The opposite of the word round is square.
