

BINTI

   bahagi ng katawan (part of the body)

   binti
   leg, especially the calf part

   kanang binti
   right leg

   kaliwang binti
   left left

   Ang ganda ng binti mo.
   Your legs are so beautiful.

   Parang binti ng elepante ang binti ko.
   My legs are like the legs of an elephant.

   Madalas sumakit ang binti ko.
   My legs often hurt.

   Paano kaya mapapaliit ang binti ko?
   I wonder how to make my legs smaller.
