

BITAK

   This is not a common word in conversation.

   biták
   crack, crevice, chink

   biták
   cavity, cleft, fissure

   bumitak
   to split, crack

   mamitak
   to dawn
   (sun splitting the sky)

   pamimitak
   dawning
   (sun slipping through a crack in the sky)
     __________________________________________________________________

   subyang
   splinter under the skin
     __________________________________________________________________

KAHULUGAN SA TAGALOG

   biták: lámat (marka na pinagsisimulan ng pagkabiyak)

   Nabibitak na at nababakbak ang asul na pintura sa dingding.
