

BITAW

   pagbitiw o paghulagpos sa kamay, pag-aalis sa pagkahawak; pagsasabong
   ng dalawang tandang, sultada
   bitaw
   release, let go

   bitawan
   to release, let go

   Bitawan mo ang bata.
   Let go of the child.

   Huwag mong bitawan ang bata.
   Don’t let go of the child.

   Huwag mo akong bitawan.
   Don’t let go of me.

   Binitawan ko ang kanyang kamay.
   I let go of her/his hand. (past tense)

   Nabitawan ko ang bola.
   I ended up dropping the ball.
