

BITIW

   pag-aalis sa pagkakahawak, bitaw; resignasyon, pagdidimiti, dimisyon

   bitiw
   to let go

   mga bagay na gusto kong bitawan
   things I want to let go of
     __________________________________________________________________

   magbitiw
   to resign

   magbitiw ng salita
   to utter a word

   Dapat silang magbitiw.
   They should resign.

   nagbitiw
   resigned

   bumitaw sa puwesto
   vacated their position, left job
