

   ____________________

Meaning of "bitiw"

bitiw •

   v.
     *
          + bumitiw (-um-) to release one's hold or grip [var. bumitaw].
            Bumitiw siya ss aking pagkakahawak. He released himself from
            my grip. magbitiw, bitiwan (mag-:-an)

   v.
     *
          + to resign, to let go [var. magbitaw, bitawan]. Nagbitiw ang
            kalihim sa kanyang katungkulan. The secretary resigned from
            his job.


