

BIYAHERO

   This word is from the Spanish viajero.

   biyahero
   traveller

   mga biyahero
   travellers

   biyahe
   journey, trip, travel, voyage

   biyaherong romantiko
   romantic traveler

    Mga biyaherong magba-bagong taon sa probinsya
   Traveler who will spend the new year in the province

   The native Tagalog word for “traveler” is manlalakbay.
     __________________________________________________________________

   Ingat sa biyahe.
   Have a safe trip!
