

BUGAW

   tagapamagitan (noon sa pagliligawan, ngayon sa prostitusyon)
   bugaw, n
   a pimp, a go-between

   Kasama ng bugaw ang kanyang mga alaga.
   The pimp is with his pets (women under his care).

   Nambubugaw siya ng mga babae.
   He pimps out girls.

   binubugaw
   is pimping
     __________________________________________________________________

   bugaw, v
   to shoo away

   binubugaw
   is shooing away

   Bugawin mo ang langaw.
   Shoo away the fly.

   past tense: binugaw
