

BUGBOG

   bugbóg: to beat up, pummel

   Binugbog ng lalaki ang kanyang asawa.
   The man beat up his wife.

   Mas gusto mo ba ang [66]bugbog o dignidad?
   Do you prefer a beating or dignity?

MGA KAHULUGAN SA TAGALOG

   bugbóg: palo, hampas, hambalos, dakdak, pangbambu, aldabis, asod

   pagbugbóg: malubha at marahas na pagdudulot ng pisikal na sakít at
   súgat sa ibang tao, hayop, o bagay sa pamamagitan ng suntok o hampas
