

BUKOD

   bukód: separate; apart; in addition to

   bukod-tangì: unique

   ibukod: to set apart, segregate

   bukúd-bukurin: to classify; separate

   Bukod dito…
   Aside from this…

   [66]pamukod: conjuction
     __________________________________________________________________

KAHULUGAN SA TAGALOG

   bukod: tangi, tangi sa rito, hiwalay, nakahiwalay

   bukod: layo, nakalayo

   bukod: tiwalag, hindi kasama, nag-iisa
