

BULAKBOL

   This word is reportedly from the English “black boy” or blackballed.

   bulakból
   vagabond

   bulakból
   truant

   nagbulakbol
   acted like a truant
   ~ ran away and
   behaved irresponsibly

MGA KAHULUGAN SA TAGALOG

   bulakbol: lakwatsero, layas, gala

   bulakbol: palaboy, hampaslupa, bagamundo (bagabundo)

   magbulakbol / nagbubulakbol, nagbulakbol, magbubulakbol, pagbubulakbol
