

BULAHAW

   bulahaw: disturbance
     __________________________________________________________________

MGA KAHULUGAN SA TAGALOG

   bulahaw: ingay na gumagambala sa katahimikan

   bulahaw: bulabog, ligalig, gulo

   bulahaw: gimbal, linggal

   Nakabulahaw sa mga kapitbahay ang hagulgulan ng mga bata.

   binulahaw bulahaw bumulahaw mabubulahaw nakabubulahaw nakabulahaw
   nakakabulahaw nambubulahaw
