

BUNGI

   The word bungì refers to having a missing tooth, particularly in a
   conspicuous position (front teeth or canines).

   mabungian
   to lose a tooth

   Nabungi ako noong bata pa ako.
   I lost a tooth when I was still young.

   ‘Pag nabungi ka, dapat mong ibaon sa lupa ang ngipin.
   When one of your teeth falls out, you have to bury it in the ground.

   Mayroong isang hari
   May alagang pusang bungi
   Ang buntot ay bali-bali
   Hintay ka muna
   Uulitin ko sandali.
