

BUNSOD

   bun·sód

   bunsód
   launch (like a boat)

   ibinunsod

MGA KAHULUGAN SA TAGALOG

   bunsód: pagpapalutang at pagdadalá sa tubig ng sasakyang-dagat

   bunsód: pagsisimula ng isang gawain o pagdiriwang

   bunsód: paglalagay ng hagdan

   bunsód: biglaang pagsalakay

   Magpasigla at magbunsod ng mga gawaing kapaki-pakinabang.

   Ang pamamaga ng internal organs ng mga batang namatay umano dahil sa
   Dengvaxia ay bunsod ng mga posibleng side effects ng bakuna.
