

BUNTÍS

   kagampan, nagdadalang-tao
   buntís
   pregnant

   Buntis ka ba?
   Are you pregnant?
   (casual)

   Buntis po ba kayo?
   (doctor to patient)

   Buntis ako.
   I am pregnant.

   Buntis yata ako.
   I think I’m pregnant.

   buntís na baka
   pregnant cow

   nagbubuntis
   is infanticipating

   pagbubuntis
   pregnancy

   Sino ang ama ng pinagbubuntis mo?
   Who is the father of the child you’re pregnant with?

   PT = pregnancy test
