

BUROL

   This word has at least two meanings, differentiated by accented
   syllable.

   buról: hill

   búrol: the wake for a dead person, before the funeral

   A wake is a watch or vigil held beside the body of someone who has
   died, sometimes accompanied by ritual observances including eating and
   drinking.

MGA KAHULUGAN SA TAGALOG

   buról: (sa heograpiya) bunduk-bundukan, gulod, dahilig, bakulod

   búrol: pinaglalamayang patay
