

BUTI

   inam, igi, bait, kagandahang-loob, galing

   bú·ti
   good

   [65]mabuti
   good

   pinakamabuti
   best

   bumuti
   to get better, improve

   butihin
   gentle, charming
   (applied to women)

   kabutihan
   goodness, benefit

   Buti nga sa ‘yo.
   Serves you right.

   makabuti
   to benefit

   mapabuti
   to improve

   pagbutihin
   to improve on

   nasa mabuting kamay
   in good hands

   To say ‘Good morning’ in Tagalog, use Magandang umaga.
