

BUWAYA

   Also known as krokodilyo and aligeytor in the Philippines.
   buwaya
   crocodile, alligator

   In Filipino culture, a buwaya is seen as tricky and greedy.
   mga buwayang pulitiko
   crocodile politicians

   buwayang-lubog
   “crocodile staying underwater”
   = traitor pretending to be good

   nabuwaya
   was cheated

   luha ng buwaya
   crocodile tears

   ang unggoy at ang buwaya
   the monkey and the crocodile

   Gaya-gaya puto maya,
   Ipakain sa buwaya.
