

BUWANG

   For the Tagalog word, see tumimbuwang.

   This is a Visayan word that even Tagalog speakers understand,
   especially since President Duterte has been using it.
   buwang
   crazy

   Buwang ka!
   You’re crazy!

   Mga buwang sila.
   They’re crazies.

   Nabuwang sila.
   They became insane.

   often shortened to buang

   There are so many ways to say ‘crazy‘ in Tagalog. You can use a
   different word for a man and a woman.
