

   ____________________

Meaning of "buwan"

buwan •

   n.
     *
          + month, moon

» synonyms and related words:

   month
   n.
     *
          + buwan

   orbit
   n.
     *
          + the path of the earth, moon, planet, etc., around the sun or
            another heavenly body: ang landas (ligiran) ng mundo, buwan,
            tala at iba pa sa paligid ng araw o ng anumang planeta, orbita


