

BUWIS

   taks, adwana, amilyarmento, rentas
   buwis
   tax, tariff, cropshare

   pederal na buwis
   federal tax

   magbayad ng buwis
   to pay tax

   mamumuwisan
   taxpayer
   (very obscure word, not in use)

   Magbayad ka ng buwis.
   Pay tax.

   Sa bansang Hapon, ang buwis na sinisingil sa isang tao ay batay sa
   kanyang kinikita. In the country of Japan, the tax charged on a person
   is based on his/her income.
