

DAAN

   The Tagalog word daan has at least two meanings in the dictionary.
     __________________________________________________________________

   daán
   hundred

   isang daán
   one hundred

   variation: raán
     __________________________________________________________________

   da·án
   road

   daán
   path, way

   dadaan
   to pass, will pass by

   Dadaan dito.
   Will pass by here.
     __________________________________________________________________

   pinagdadaanan
   trials or suffering one is undergoing

   pinagdaanan
   what one has undergone or suffered

   May pinagdaanan kami ni Rosa.
   Rose and I have undergone something.
   We’ve gone through something (together).
     __________________________________________________________________

MGA KAHULUGAN SA TAGALOG

   daán: pook na nauukol sa paglakad o pagtakbo ng tao, hayop, o sasakyan
   patúngo sa isang pook

   daán: bakás o palatandaang naiwan sa pagdaraan

   daán: sanhî

   daán: paraan o sistema

   daán: pamílang na katumbas ng sampung sampu
     __________________________________________________________________

   daán: sumaglit o pumunta sa isang pook nang panandalian lámang

   daanán, dumaán, idaán, magdaán
     __________________________________________________________________

   daán: nakalipas; yumáo; pumána
     __________________________________________________________________

   dáan: paghingi

   halimbawa: “Makiraan ka ng sukà.”
