

DAKDAK

   taktak, baon, tulos ng matulis na bagay sa lupa; tupada, ilegal na
   sabong; palo ng ulo ng espada, tungkod o kulata ng baril o riple
   dakdak
   to chatter nonstop

   Dakdak nang dakdak…
   Just going on chattering….

   madakdak
   talkative, overly chatty

   napadakdak: napadaldal, dumaldal
     __________________________________________________________________

   Related Tagalog words: madada, madaldal
