

DAKO

   direksiyon, patunguhan, gawi, puntahan

   sa dakong gitna
   towards the center
   toward the middle

   dako: direction, way

   dako: region, spot, place

   dumako: to go somewhere, towards something
     __________________________________________________________________

   Kailan nga ba sa buhay mo, ika’y nadako sa aklatan?
   When in your life have you been towards the library?

   nadako ~ dumako ~ napadako ~ napapunta sa direksyong yaon
