

DALO

   This word has at least two different meanings — the first one slightly
   more common that the other.
     __________________________________________________________________

   daló: presence

   dumaló: to attend

   daluhán: to attend

   dinaluhan: attended
     __________________________________________________________________

   daló: help
     __________________________________________________________________

MGA KAHULUGAN SA TAGALOG

   dalo: asisti, asistensiya, pagdating, pagdalaw, punta, tungo

   dalo: tulong, damay, saklolo, sokoro
