

DAMDAM

   pakiramdam, dama, wari, nararamdaman sa kalooban o pag-iisip
   damdám
   take offense, feel resentment

   Huwag kang magdamdam.
   Don’t take offense.

   Huwag mong damdamín ito.
   Don’t feel resentment over this.

   Hindi mo kailangang damdamin ito.
   You don’t need to be resentful over this.

   Dinamdam ko ang sinabi nila.
   I took offense to what they said.
   They offended me.

   Related Tagalog word: [66]damdámin (feeling)
