

DAMI

   kantidad, malaking bilang, rami
   dami
   amount, quantity

   dami
   lots

   marami
   a lot, many, plenty

   Ang daming tao dito!
   There are a lot of people here.

   Andami = Ang dami

   Maraming taong dumating.
   A lot of people came.
     __________________________________________________________________

   karamihan
   most, the majority

   dumami
   to increase in number
