

DANAK

   danak: spilling (of blood)

   danak: agos, bugalwak, tulo, bubo (tulad ng dugo)

   dumanak: to flow; pour out

   dumanak: poured out, dripped

   Dumanak ang kanilang dugo sa lansangan.
   Their blood flowed in the streets.

   Ang kanilang dugo ay dumanak nang walang kabuluhan.
   Their blood flowed senselessly.

   Dadanak ang dugo dito.
   Blood will spill here.
   There will be blood here.
