

DAPAT

   pronounced DAH-PAHT

   kailangan, nararapat, marapat
   dapat
   should, ought to, must

   Dapat mo itong gawin.
   You must do this.

   Hindi mo dapat itong gawin.
   You shouldn’t do this.

   Dapat kumanta ka.
   You must sing.

   Dapat matulog ka na.
   You must sleep already.

   Hindi ka dapat matulog dito.
   You shouldn’t sleep here.

   Non-standard spelling variations: Dpat, Dpt, Dapt
