

DATAPWA

   This is an old Tagalog word for “but” or “however.”

   variations: datapuwa’t datapwat datapuwa datapuwat datapwa

   The most commonly used word for “but” these days is the Spanish-derived
   [66]pero. The native Tagalog [67]ngunit now sounds formal.
     __________________________________________________________________

KAHULUGAN SA TAGALOG

   datapwa: nguni, subali, gayunman, pero

   misspelling: dataputwa’t
