

DAYO

   dayo (noun): visitor; stranger; foreigner

   dayuhan (adjective): foreign, alien

   dayuhan (noun): foreigner alien

   dumayo (verb): to go to a faraway place; migrate

   dinadayo: is being visited by people from faraway
     __________________________________________________________________

MGA KAHULUGAN SA TAGALOG

   dayo: dayuhan, banyaga, estranghero, alyen; ang nagsadya

   dayuhan: dayo, banyaga, estranghero, alyen; taga-ibang bansa o lunan

   mandarayo, dumarayo
