

DAYUHAN

   root word: dáyo

   da·yú·han
   foreign, alien

   dayúhan
   foreigner

   mga dayúhan
   foreigners, aliens

KAHULUGAN SA TAGALOG

   dayúhan: tao na taga-ibang pook o bansa o kayâ’y hindi kilála sa pook
   na kaniyang pinuntahan

   Kung dati’y lakas-paggawa ang inilalako ng ating estado sa iba’t ibang
   bansa, ngayo’y unti-unti nang nanghihikayat ng mga dayuhang
   mangangalakal na mamuhunan sa Pilipinas.
