

DIGMAAN

   root word: digma

   digma
   war, warfare, battle

   digmaan
   the act of warring

   digmain
   to wage war on

   mandirigma
   warrior

   nakipagdigma
   went to war against others

   Malungkot ako kapag may digmaan.
   I’m sad when there’s war.

   Digmaang Malamig
   Cold War

   Digmaang Pilipino-Amerikano
   Philippine-American War

   The Spanish-derived Filipino word for ‘war’ is gera.
