

DUKHA

   duk·hâ

   dukhâ
   poor, needy

   karukhaán
   poverty; lack, deficiency
     __________________________________________________________________

MGA KAHULUGAN SA TAGALOG

   dukha: maralita, mahirap, pobre

   dukhâ: kúlang na kúlang sa mga pangangailangan sa búhay

   “dukhang maralita”

   Itinuro sa mga dukha na gantihan nila ng tinapay kapag pinupukol sila
   ng bato ng mga mayayaman, hindi ba?

   “Sinunod ng mga dukha ang aral na iyan sa habang panahon.”
