

DUMAL

   dú·mal

   karumal-dumal
   nasty

   karumal-dumal
   loathsome

   mga karumal-dumal na krimen
   heinous crimes

KAHULUGAN SA TAGALOG

   dúmal: pagiging lubhang hamak at nakahihiya ng kalagayan, kaligiran, o
   pangyayari

   Sa kabilang banda, mainam na ito upang hindi na lumaganap ang mga
   karumal-dumal na krimen sa ating bansa.

   Ilang senador ang nagpanukala na ibalik sa habambuhay na pagkabilanggo
   ang sinumang nagkasala ng karumal-dumal na krimen?
