

DUMOG

   dú·mog: to crowd, mob

   dinumog: crowded into something, mobbed
     __________________________________________________________________

MGA KAHULUGAN SA TAGALOG

   dúmog: sama-samang pagdalo

   dúmog : lubhang pagkaabala sa gawain, lulong

   dúmog : pagtutulong-tulong ng marami sa pakikipag-away o sa paggawa

   dúmog : paghugos o pagligid ng masiglang pulutong sa tao, hayop, pook,
   at iba pa

   dúmog : pagkaabalá o lulóng sa gawain

   úmog, dumúgin, mandúmog, nagdumugan
