

DUNONG

   dúnong: knowledge

   marúnong: learned, intelligent

   karunúngan: wisdom, knowledge; talent, ability

   kasindunong / kasingdunong: as smart as

   kilábot sa dunong: terrifyingly smart

   misspelling: dunog

MGA KAHULUGAN SA TAGALOG

   dúnong: katalinuhan, katalasan ng isip, katalisikan, unawa, intindi

   dúnong: katangian o kalagayan ng pagiging matalino o matalas ang isip

   dúnong: anumang nagpapakilála ng malawak na kaalaman
