

ESTERO

   This word is from the Spanish language.

   estéro
   estuary

   estéro
   foul ditch

   The second definition refers to a canal, often filled with dirty water,
   along the side of a road.

   esterong nilalamok
   mosquito-infested ditch

MGA KAHULUGAN SA TAGALOG

   estéro: daluyan ng tubig na pinagtatagpuan ng taog at ng ilog

   táog: pagtaas ng tubig sa dagat

   estéro: malakíng kanal, malimit iugnay sa barado, maputik, at mabahòng
   daluyan
