

Funny Tagalog Quotes

   Some of these Tagalog quotes lose their funniness after being
   translated into English because the puns are very specific to the
   language. 🙂

   Ang pag-ibig ay parang ketsap. Matamis pero maraming nakikisawsaw.
   Love is like catsup. Sweet, but a lot of people want to co-dip.
   – joke spoken by Senator Miriam Defensor-Santiago (1945-2016)

   Ibenta mo na bahay mo. Tutal nandito ka na nakatira sa puso ko.
   Sell your house. You’re already living here in my heart.
   (You already have a home in my heart.)

   Sana iksam mo na lang ako, para sagutin mo rin ako.
   Wish I were your exam, so you’d answer me.
   Nakalimutan ko ang pangalan mo. Pwede bang tawagin na lang kitang akin?
   I forgot your name. Could I just call you mine?

   Ang pag-ibig parang bayad sa dyipni. Minsan, hindi nasusuklian.
   Love is like jeepney fare. Sometimes you don’t get anything back.

   Gaano ka katangkad? Paano ka nagkasya sa puso ko?
   How tall are you? How were you able to fit in my heart?

   Ang taong manhid, parang bato. Hindi nasasaktan, pero nakakasakit.
   An insensitive person is like a stone. Cannot be hurt, but can hurt.

   Farsighted ka ba? Kasi ang layo ng tingin mo. Nandito lang naman ako.
   Are you farsighted? Because you’re looking faraway. I’m just here.

   Ang pag-ibig parang sakit. Tatamaan ka sa panahong hindi mo inaasahan.
   Love is like a sickness. It’ll hit you at a time you don’t expect it.

   Huwag mong ipagsiksikan ang sarili mo sa taong ayaw sa iyo. Hindi ka
   sardinas.
   Don’t push yourself on people who don’t like you. You’re not a sardine.

   Timba ako. Gripo ka. Kaya ‘pag napuno ako, papatayin kita.
   I’m a bucket. You’re a faucet. So when I get full, I will “kill” you.
