

GAANO

   Gaano kadalas ang minsan?

   gaano
   how much (quantity)

   magkano
   how much (price)
     _______________________________________________________________________________________________________________________________________________________________

   gaano man
   however

   kahit gaano
   no matter how much
     _______________________________________________________________________________________________________________________________________________________________

   Gaano kadalas?
   How often?

   Gaano katagal?
   How long a time?

   Gaano katagal mo na akong gusto?
   How long have you liked me?
