

GAHASA

   This word originally referred to assault in general. It is now
   understood to mean rape.

   gahasa
   rape

   ginahasa
   was raped

   Ginasaha siya ng sundalo.
   She was raped by the soldier.

   panggagahasa
   act of rape

   gawang marahas; abuso; pagwasak sa puri ng babae
     __________________________________________________________________

   Less common Tagalog synonym: panggagahis
