

GALAW

   kilos; masining na pagkilos o pagganap ng isang artista kung umaawit,
   nagsasayaw, o nagsasalita

   galaw
   movement

   paikot na galaw
   rotary movement

   gumalaw
   to move

   Huwag kang gumalaw.
   Don’t move.

   igalaw
   to move

   Igalaw mo ang iyong kamay.
   Move your hand. (Doctor to patient.)

   galawin
   to move, disturb something

   Huwag mo itong galawin.
   Don’t touch this.

   di-magagalaw
   immovable
