

GALA

   libot, laboy, pasyal; paglalayag, biyahe

   galà
   rove, wander

   gumalà
   to roam around

   Gala lang nang gala…
   Just roaming and roaming about…
     __________________________________________________________________

   Mayroon ding salita sa English na “gala” na ang ibig sabihin ay
   pagdiriwang, pista o kasayahan. Depinisyon sa Ingles: a social occasion
   with special entertainments or performances.
