GANAP

   lubos, buo, perpekto, kompleto; nagawa na, natapos na, natupad na;
   yari, tapos; tiyak na oras, eksakto

   ganáp
   complete, perfect, total, thorough

   ganáp na monarkiya
   absolute monarchy

   ganáp
   fully, completely, entirely

   ** kaganapan **
   fulfillment, occurrence

   ganapín
   fulfill, perform, carry out, accomplish

   magaganap
   will happen, will occur

   tagapagpaganap
   executive

   also gampan
