

GANITO

   ganiri, gayari
   ganito
   like this

   ganito
   in this manner

   sa ganito
   thus

   Ganito mo gawin.
   Do it like this.

   Gawin mong ganito.
   Make it like this.

   ganitong libro
   this type of book

   Gusto ko ng ganitong libro.
   I want this kind of book.
     __________________________________________________________________

   ganyan
   like that

   ganoon / ganun
   like that over there
