

   ____________________
   (BUTTON)

Meaning of "gatong"

gatong •

   n.
     *
          + firewood, fuel maggatong, igatong (mag-:i-)

   v.
     *
          + to feed with fuel, to put into the fire as fuel. Kumuha ka ng
            kahoy para igatong. Get some wood for fuel.

» synonyms and related words:

   fuel
   n.
     *
          + anything that can be burned to make a useful fire: gatong,
            panggatong


