

GATOL

MGA KAHULUGAN SA TAGALOG

   gatól: pagkauntol ng banayad na galaw, gaya ng pagtama ng kutsilyo sa
   butó ng isang hinihiwa

   gatól: pagsagka ng isang bagay na hinihila sa bakô-bakông daán

   gatól: magaspang, hindi pantay, bukól-bukól, o buhól-buhól

   gatól-gatól: pahinto-hinto hal gatól-gatól na pagsasalita

   gatól-gatól: bakô-bakô

   gatól-gatól: maraming pekas, tulad ng bulutong-tubig
