

GAYAK

   gayák: decoration, trimmings, intention

   gayák: dressed up

   nakagagayak: decorative

MGA KAHULUGAN SA TAGALOG

   gayák: palamutî

   gayák: áyos

   gayák: bíhis

   * gayák: paghahanda sa papaalis

   gayakán, gumayák, igayák, mággayák, nakagagayak

   May gayak ang mga kalye. May mga arko at banderitas sa daan.

   Ang palasyo ni Prinsesa Urduja ay magagayakan ng sari-saring palamuti.
