

GINANG

   misis, senyora, ang maybahay, matrona
   Ginang
   title for a married woman

   Ginang Layug
   Mrs. Layug

   Unang Ginang
   First Lady (wife of the president)

   Kay Ginang Dimaandal
   To Mrs. Dimaandal

   Para Kay Ginang Macaraeg
   For Mrs. Macaraeg

   Filipinos abbreviate the Tagalog word Ginang as Gng.

   Gng. Cruz = Ginang Cruz
   Mrs. Cruz

   Filipinos use the title Binibini for unmarried women and Ginoo for men
   in general.
