

GITNA

   sentro, kalagitnaan
   gitna
   middle, center

   Gitnang Asya
   Central Asia

   sa gitna ng
   in the midst of, among

   sa gitna ng dagat
   in the middle of the ocean

   sa gitna ng ilog
   in the middle of the river

   sa gitna ng bagyo
   at the center of the storm

   sa gitna ng panganib
   in the midst of danger
     __________________________________________________________________

   kalagitnaan ng gabi
   middle of the night
