

GULO

   guló
   tumult, commotion, panic, riot

   Ang gulo!
   So much disorder!

   naguguluhan
   perplexed, confused

   Naguguluhan ako.
   I’m confused.
     __________________________________________________________________

   magulo
   confused, muddled, disorderly

   magulong buhok
   messy hair

   Magulong-gulo ang isip ko.
   My mind’s such a mess.

   Magulo ang buhay sa Pilipinas.
   Life is complicated in the Philippines.
