

GUPO

   ruin, ruins, ruined

   overpower

MGA KAHULUGAN SA TAGALOG

   gupo: pagkabagsak, paggiba, pagkalugso, pagtumba

   gupo: pagkatalo

   iginupo, iginugupo, naigupo, igugupo

   Ang pagkagupo, ayon sa Pahayag 18:2, ay ang pagiging tahanan ng mga
   masasamang espiritu. Ang tungkulin mo ay mapuspos ng mga mabubuting
   bagay mula sa Salita, sa Espiritu Santo at sa kapangyarihan ng Diyos.
