

HABA

   This word has multiple meanings.

   habà
   length

   mahaba
   long

MGA KAHULUGAN SA TAGALOG

   habà: sukat sa pagitan ng magkabilâng dulo
   habà:: tagal ng pangyayari o pagsasagawâ ng anuman

   habâ: may hugis na mahabà kaysa karaniwan
   habâ: mahabà at manipis

   habâ: isdang-alat (Ablennes hians) na pahabâ ang katawan, karaniwang
   may sukat na 43.5–50 sm, patulís ang bibig na tíla tukâ, at kulay
   lungtian at putî ang katawan
