

HAGINIT

   ha·gi·nít

   haginít: cracking sound, swishing sound

   humaginít: to swish by

   pahaginitín: to crack, cause to make a sharp noise

MGA KAHULUGAN SA TAGALOG

   haginit: tunog ng pagpalo o paglalatigo

   haginit: ingay ng hanging mabilis o ng mabilis na sasakyan

   haginit: harurot, hagibis

   paghaginit: pagharurot, paghagibis

   haginít: matinis na tunog ng isang mabilis na pagdaan ng hangin o ng
   isang mabilis na sasakyan

   haginít: hagupít
