

HALAY

   hálay: obscenity

   hálay: rape

   hálay: blasphemy

MGA KAHULUGAN SA TAGALOG

   hálay: salita, kilos, o ugali na lumalabag sa batas ng kagandahang-asal
   at moralidad

   hálay: gahasà

   hálay: pagkakasála dahil sa pagtuturing sa sarili bílang isang diyos

   Nagsampa ng kasong panggagahasa kahapon ang isang 18-anyos na katulong
   laban sa kanyang amo na umano ay apat na beses na nanghalay sa kanya sa
   Makati City.
