HANAP

   bagay na nais makita, pagsaliksik
   hanap
   to search, look for, find

   Ikaw ang hanap ng puso ko.
   You are what my heart is looking for.

   Hanapin mo dito.
   Look for it here.

   Hanapin mo sa likod.
   Look for it in the back.

   Hanapin mo siya.
   Find him. = Find her.

   Mahirap hanapin.
   Hard to find.

   hanap-hanapin
   to miss something absent

   hanapbuhay
   “find life” = livelihood
