

   ____________________

Meaning of "hango"

hango •

   v.
     *
          + humango (-um-) to appropriate a certain amount of goods

   v.
     *
          + maghango, hanguin (mag-:-in) to remove something being cooked
            from the fire, to adapt from literary material, to save
            someone from something. Hanguin mo siya sa hirap. Help him out
            (of his difficulties).


