

HARAP

   unahan, bukana, delantera, kasalungat ng likod (likuran)

   haráp
   front

   sa haráp ng panganib
   in the face of danger

   sa haráp ng tindahan
   in front of the store
     __________________________________________________________________

   haráp
   to face

   harap-harapan
   face-to-face

   Harapin mo ako.
   Face me.

   Harapin mo ang katotohanan.
   Face the truth.
     __________________________________________________________________

   iharap
   to present

   iharap sa Senado
   present to the Senate
     __________________________________________________________________

   haráp
   euphemism for pubic area
