

HAWA

   paglipat ng sakit sa iba, lalin

   hawa
   infection, contagion

   mahawa
   to become infected

   nakakahawa
   contagious, infectious

   Nakakahawa ba ang bulutong?
   Is chickenpox contagious?

   Nakakahawa ang sakit ni Ana.
   Ana’s disease in contagious.

   Mag-ingat ka. Baka mahawa ka.
   Be careful. You might catch it.

   Nahawa ako sa iyo.
   I caught it from you.

   Hinawaan mo ako.
   You infected me.
