

HAWAK

   taglay sa kamay, tangan, taban
   hawak
   hold, grasp

   Humawak ka.
   Hold on (to something).

   paghahawak
     __________________________________________________________________

   hawakan
   to take hold of

   Hawakan mo ito.
   Hold this.
     __________________________________________________________________

   hahahawakan
   will hold
   Hahawakan ko ang kamay mo.
   I’ll hold your hand.
     __________________________________________________________________

   hinawakan
   held

   unang bagay na hinawakan mo sa araw na ito
   first thing you touched on this day

   Hinawakan ko ang kamay niya.
   I held his/her hand.
     __________________________________________________________________

   ang mayhawak ng karapatang-ari
   ang mayhawak ng karapatan sa akda
   the copyright holder
     __________________________________________________________________

   The Tagalog word for one kind of ‘touch’ is hipo.
