

HAYAG

   deklarasyon, manipesto, ekspresyon
   hayág
   easily seen, public,
   exposed view
   ihayag
   disclose, reveal, divulte

   Kilusan sa Pilipinas para sa Malayang Pamamahayag
   Philippine Movement for Press Freedom

   pahayagan
   newspaper
     __________________________________________________________________

   The word hayág by itself is not as common as [66]pahayag (as in a
   statement issued by a politician, celebrity or organization) and
   pahayagan.
