

HILAKBOT

   hi·lak·bót

   hilakbot
   terror

   hilakbot
   fright

   hilakbot
   extreme fear

   nakakahilakbot
   frightening

   kahila-hilakbot
   extremely frightening

   kahilahilakbot na pangyayari
   extremely scary occurence

   ikapapanghilakbot
   shall be the cause of terror

   ikapanghilakbot
   be the cause of terror

   ikinapanghila-hilakbot
   was the cause of terror

MGA KAHULUGAN SA TAGALOG

   hilakbot: gulilat, gulat, takot, nakakahindik na damdamin, kilabot

   hilakbót: pakiramdam na pagtinghas ng balahibo dahil sa sindak.

   nakapanghihilakbot, nanghihilakbot, nanghilakbot, pagkahilakbot,
   panghihilakbot, nakahihilakbot, pinanghihilakbot (kinakatakutan),
   pinaghihilakbot, paghihilakbot, manghilakbot
