

HILA

   This word is from the Spanish girar.

   hila
   pull

   isang hila
   one pull

   hilahin
   to pull

   Hilahin mo ito.
   Pull this.

   Hilahin mo ako.
   Pull me.

   Ang kasulungat ng hila ay tulak.
   The opposite of pull is push.

   hatak, batak, higit, baltak; kaladkad; ang kargada bilang isang yunit
   ng pagsukat para hilahin; ang bagay na hila-hila; himok, hikayat,
   yakag, kayag, ganyak, halina; isang uri ng ketong
