

HILING

   petisyon, pakiusap, pamanhik, paghingi, pithaya, pita, hinihingi, samo,
   panikluhod

   hiling
   request

   hiling
   claim, application

   Hinihiling ko sa iyo.
   I am begging you.

   hilingin
   to petition, ask earnestly

   kahilingan
   request, petition, application

   kahilingang maging kaibigan
   request to befriend

   Ang tanging hiling ko ay mahalin mo ako kahit saglit.
   My only wish is that you love me even for a moment.
