

HILOM

   hilom, maghilom: to heal (wound)

   hilom, maghilom: to close up (an opening)

   The line “Maghihilom ang lahat ng sugat” appears in the Filipino
   Christmas song “Star ng Pasko.”
     __________________________________________________________________

MGA KAHULUGAN SA TAGALOG

   hilom (sa larangan ng medisina): pagsasara o paggaling ng sugat, bahaw

   hilom: pag-aagaw-dilim

   humilom: pumeklat
