

HIMIG

   This word has at least the two meanings, the first one more common than
   the second.

   hímig: tune, melody; note

   hímig: humidity
     __________________________________________________________________

KAHULUGAN SA TAGALOG

   himig: tono, melodia, indayog, higing, ritmo

   himig: dimig, halumigmig

   himig: ebaporasyon, pagkaiga, singaw, unang pagbalong ng tubig sa
   ginagawang balon
