

HINAING

   root word: daíng
   hi·na·íng
   supplication

   mga hinaing ng puso
   supplications of the heart

   hinaing
   complaint, grievance

   mga hinaing
   complaints, grievances

   A common Filipino word for “complaint” is reklamo.

MGA KAHULUGAN SA TAGALOG

   hinaíng: pagpapahayag ng sákit o lungkot

   hinaíng: pagpapahayag ng hindi kasiyahan o samâ ng loob

   pakiusap, luhog, hinakdal, samo, pamanhik, panikluhod
