

HINGÁ

   respirasyon, paghinga, hininga
   hingá
   breath

   paghingá
   respiration

   hiningá
   what was breathed out
   = breath

   Ang baho ng hiningá mo!
   Your breath stinks!

   Humihingá pa ba iyan?
   Is it still breathing?

   Humihingá pa rin.
   Still breathing.

   Humihingá pa rin ako.
   I’m still breathing.

   Humingá ka nang malalim.
   Breathe deeply. /Inhale deeply.

   Nawalan ng hiningá.
   Ran out of breath.

   See also [66]pahingá.
