

HINTO

   Stop in Tagalog!

   tigil, para, tahan, himpil, humpay
   hinto
   stop, halt, pause

   Hinto!
   Stop!
     __________________________________________________________________

   huminto
   to cease, stop

   Ayaw huminto sa kakaiyak.
   Doesn’t want to stop crying.
     __________________________________________________________________

   ihinto
   to cause to stop

   inihihinto, inihinto, ihihinto
   is stopping, stopped, will stop
     __________________________________________________________________

   paghinto
   stoppage, intermission

   hintuan
   stopping place
