

HIPAN

   root word: hihip

                                    hipan
                                   to blow

                             hipan ang trumpeta
                              blow on a trumpet

                             hinipan ang kandila
                             blew on the candle

                              hinipan ng hangin
                              blown by the wind

