

HIYAS

   This is from the Spanish word joyas.

   hi·yás
   gem, jewel

   mumurahing hiyas
   cheap trinket

   hiyas ng tahanan
   “jewel of the home” = maiden

   hiyas ng pagkababae
   “jewel of womanhood” = honor

   hiyas
   literary euphemism for female genitalia

MGA KAHULUGAN SA TAGALOG

   hiyás: palamuting pangkatawan, malimit gawâ sa mámaháling metal at
   tinatampukan ng pambihirang bató

   hiyás: mámaháling bató

   hiyás: isang tao o bagay na may mataas na pagtatangi
