

HUGIS

   korte, hubog, anyo, tabas, pigura, porma
   hugis
   shape, form, figure

   hugis
   mold, model

   Anong hugis nito?
   What’s the shape of this?

   Bilog ba ang hugis?
   Is the shape round?

   humugis
   to form, shape

   hugis-kandila
   candle-shaped

   hugis-tao
   human form

   hugis-tagilong
   pyramidal shape

   Shapes in Tagalog Shapes in Tagalog

   A Spanish-derived word for “shape” is korte.

   A related Tagalog word is anyo (form).
