INYO

   inyo
   your, yours (plural)

   ang iyong bahay
   your house (speaking to one person)

   ang inyong bahay
   your house (speaking to more than one person)

   Ito ay iyo. Ito’y iyo.
   This is yours. (speaking to one person)

   Ito ay inyo. Ito’y inyo.
   This is yours. (speaking to more than one person)

   Sa inyo ba ito?
   Does this belong to you folks?

   Sa inyo ‘to.
   This belongs to you guys.

   The singular form of the Tagalog word inyo is iyo (yours).
