

IPON

   tipon, pagsasama-sama, koleksiyon
   ipon
   gather, collect

   nakaipon
   was able to save (money, etc)

   Baka hindo ako makaipon.
   I might not be able to save.

   ipunin
   to gather, collect, save

   Kailangan mong mag-ipon ng pera.
   You need to save money.

   Nag-iipon ako ng pera.
   I’m saving money.

   Iipunin ko ang lahat ng aking matatanggap.
   I’ll save all I will receive.

   Kailangang mag-ipon ng tubig.
   One has to collect water and put it aside.
