

ITIM

   kasulangat ng puti
   itim
   black

   itim na pusa
   black cat

   itim na aso
   black dog

   Ang itim!
   So black!
     __________________________________________________________________

   [66]maitim
   blackish, dark

   maitim na tuhod
   dark-colored knee
     __________________________________________________________________

   Ang kasalungat ng itim ay puti.
   The opposite of black is white.
