

ITO

   The Tagalog word ito is often shortened to ‘to in conversation.
   ito
   this

   Ano ito?
   What is this?

   Ito ay kahon.
   This is a box.

   Ito ay malaki.
   = Malaki ito.
   This is big.

   Itong kahon ay malaki.
   = Malaki itong kahon.
   This box is big.

   Mas malaki ito kaysa sa lapis.
   This is bigger than the pencil.

   Kanino ito?
   Whose is this?

   Sa akin ito.
   This is mine.

   Sa iyo ito.
   This is yours.
