

KABABALAGHAN

   root word: balaghán, meaning “wonder” or “amazement”

   kababalaghán
   mystery, miracle, marvel

   kababalaghán
   weird phenomenon

   Ano ang kababalaghang ito?
   What is this mysterious thing?

   Naniniwala ba kayo sa kababalaghan?
   Do you believe in miracles?
     __________________________________________________________________

   The Spanish-derived Filipino word for “miracle” is milagro.
