

KABIT

   nakadikit, nakasabit, nakakapit, sugpong, hugpong

   kabít
   attached, connected

   ikabít
   to fix, fasten

   Huwag mong ikabit ang pangalan mo dito.
   Don’t attach your name to this.

   Ikabit ang inyong sinturong pangkaligtasan.
   Fasten your seatbelts.
     __________________________________________________________________

   kolokyal na kahulugan: kerida, bata, kalunya, babae

   kabít
   common-law wife

   kabít
   mistress

   kabit na babae
