

KAGYAT

   dagli, agad, pagdaka, agad-agad, kaginsa-ginsa, karaka-raka, bigla
   kagyat
   instantly

   kagyat
   immediate

   kagya’t
   suddenly

   Ang Estado ay dapat maglaan ng kagyat at sapat na pangangalaga, mga
   benepisyo, at iba pang mga anyo ng tulong sa mga beterano ng digmaan.
   The State shall provide immediate and adequate care, benefits, and
   other forms of assistance to war veterans.
