

KALAT

   ang mga bagay na naiwang nakakalat; sambulat

   hiwa-hiwalay, sabog; alam na, laganap
   kalat
   litter, disorder, spread out

   Ang laking kalat nito.
   This is a big mess.
     __________________________________________________________________

   nakakalat na graba
   loose gravel

   nakakalat na basura
   strew-about garbage
     __________________________________________________________________

   kalát
   stray, sporadic, scattered

   Kalát ang pag-iisip.
   Mind is scattered.
     __________________________________________________________________

   makalat
   messy

   Makalat ang kuwarto.
   The room is messy.
     __________________________________________________________________

   kumalat
   to spread, circulate, scatter

   Kumalat ang balita.
   The news spread.

   Kumakalat ang balita.
   The news is spreading.
     __________________________________________________________________

   nagkalat ng baho
   (someone) spread foul odor
     __________________________________________________________________

   ikalat
   to spread

   Ikalat ito.
   Spread/Circulate this.
