

KALABAW

   Kalabaw / Carabao

   Scientific name: Bubalus bubalis carabanesis

   kalabaw
   carabao

   The so-called water buffalo of the Philippines, the carabao has
   officially been officially recognized by the government as the national
   animal of the country!
     __________________________________________________________________

   KALABAW
   Masdan ang kalabaw
   Habang nakasingkaw
   Sa ginta ng linang
   Sa init ng araw
   Laging kaibigan.

   — Landicho
