

KALAMIDAD

   This word is from the Spanish calamidad.

   ka·la·mi·dád
   calamity

   natural na kalamidad
   natural calamity

   mga natural na kalamidad
   natural calamities

MGA KAHULUGAN SA TAGALOG

   kalamidád: malubhang kapahamakan, gaya ng bagyo, lindol, pagsabog ng
   bulkan, o sunog

   sakuna, kapahamakan, aksidente, disgrasya, katastrope, malaking hirap,
   kasamaang-palad, matinding tiisin
