

KALADKAD

   ka·lad·kád

   kaladkád
   drag

   kinaladkad
   dragged

MGA KAHULUGAN SA TAGALOG

   pagkaladkád: marahas, buong lakas, at naghihirap na paghila o pagbatak
   sa tao, hayop, o bagay

   ikaladkád, kaladkarín

   kaladkád: bagay na hinihila o binabatak

   pagkaladkád: paraan ng pagkuha ng tulya o susô sa pamamagitan ng
   pagka-laykay sa ilalim ng tubigan

   kaladkád: sa pangingisda, lambat na panghalukay
