

KALBARYO

   This word is from the Spanish calvario.

   kalbaryo
   calvary

   Calvary (written with a capital “C”) is the hill near Jerusalem on
   which Jesus was crucified. The name is Latin for “Place of the Skull”;
   it is also called Golgotha.

   In art, calvary is a sculptured representation of the Crucifixion,
   usually erected in the open air.

   In general usage, calvary is an experience or occasion of extreme
   suffering, especially mental suffering.
