

KAMALAYAN

   root word: málay (meaning: consciousness)

   kamalayán
   awareness

   kamalayán
   awareness

   kamalayang pansibiko
   civic consciousness

   The following terms are not commonly used:

   kubling-malay
   subconsciousnes

   kubling-kamalayán
   subconsciousnes

MGA KAHULUGAN SA TAGALOG

   kamalayán: kalagayan ng pagiging gisíng at alám ang nása paligid

   kamalayán: pagkaalam o kaalaman sa anuman

   kamalayán: ang pagkabatid ng isip sa sarili at sa daigdig
