KAMBING

   This can also be a slang word for a gigolo or pimp.

   kam·bíng
   goat

   mga kambing
   goats

   gatas ng kambing
   goat’s milk

   gatas ng baka
   cow’s milk

   Kumakain ng damo ang kambing.
   The goat is eating grass.

MGA KAHULUGAN SA TAGALOG

   kambíng: hayop (genus Capra) na kauri ng tupa ngunit may sungay at
   hindi makapal ang balahibo

   kambíng: gigolo o binatang palikero na umaasa sa kíta ng mga babae niya
