

KAMTAN

   root word: kamit
   kamtan
   get, obtain, attain

   kinamtan
   got, obtained

   kinakamit
   (present progressive)

   nakamit
   obtained

   makamtan ang tagumpay
   achieve success

   upang makamtan ang minimithing kasarinlan
   in order to obtain the independence being longed for
     __________________________________________________________________

   Related Tagalog word:
   abot
   reach
