

KANILA

   This is a pronoun.
   kanila
   theirs

   Ito ay kanila.
   This is theirs.

   Kanila ito.
   This is theirs.

   Kanila ba ito?
   Is this theirs?

   Oo, kanila ‘yan.
   Yes, it’s theirs.

   ang kanilang bahay
   their house

   kanila-kanilang
   to each their own

   Mayroon silang kani-kanilang problema.
   They each have their own problems.

   The singular form of kanila is the word kanya.

   The Tagalog word for ‘they’ is sila.
