

KANLUNGAN

   root word: kanlong

   mga lugar na posibleng pinagkakanlungan ng mga terorista
   places that may be harboring terrorists

   mga kampong pinagkakanlungan ng mga babae
   women refugee camps

MGA KAHULUGAN SA TAGALOG

   kanlúngan: silungán

   kanlúngan: pook na maaaring taguán o kublihán

   kanlóng: natatakpan o nalililiman

   kanlóng: nakakubli sa likod ng kalasag at iba pang harang, kayâ hindi
   makíta o makakíta
