

KANTA

   This word is from the Spanish canta.

   kantá
   to sing

   kanta
   song

   The native Tagalog word for ‘song’ and ‘to sing’ is [66]awit.

   Kumanta sila.
   = Umawit sila.
   They sang.

   Kumanta tayo.
   Let’s sing.

   Marunong akong kumanta.
   I know how to sing.

   kantahing bayan
   = awiting bayan
   folk song, folksong

   Anong kakantahin natin?
   What are we going to sing?

   ikinanta
