

KANYA

   orthodox Tagalog spelling: kaniya

   kanya
   his, her, its, hers

   Ito ay kanya.
   This is hers/his.

   Kanya ito.
   This is hers/ his.

   Kanya ba ito?
   Is this hers/his?

   Oo, kanya ‘yan.
   Yes, it’s hers/his.

   ang kanyang kamay
   her/his hand

   kaniya-kaniyang
   to each his own

   Kanya-Kanyang Bayad (KKB)
   each to pay his own way

   The plural form of kanya is the word kanila.
