

KARANIWAN

   root: daniw (not a common word by itself)

   karaniwan
   commonplace, normal, usual, average

   karaniwang tao
   common person, average person

   pangkaraniwan
   ordinary

   di-pangkaraniwan
   out of the ordinary, unusual

   pangkaraniwang araw
   ordinary day

   di-karaniwang
   special

   Karaniwan ko itong nararamdaman sa tuwing ako’y nagbloblog.
   I usually feel this every time I blog.
