

KARUNUNGAN

   root word: dúnong

   karunúngan
   wisdom

   karunúngan
   knowledge, talent, ability

   karunúngang bayan
   folk wisdom

   katutubong tradisyon
   native tradition

   mga salawikain / kawikain
   proverbs

   sawikain
   proverbs

   kasabihan
   sayings

   Ano’ng karapatan mong mangaral at saan mo kinukuha ang iyong
   karunúngan?
   What right do you have to lecture and where did you get your wisdom?
