

KASAPI

   root word: [66]sapi

   kasapi
   member of an organization

   mga kasapi
   members

   mga dating kasapi
   past members
     __________________________________________________________________

MGA KAHULUGAN SA TAGALOG

   kasapi: miyembro, kasosyo, kasama, kagawad, kaanib
     __________________________________________________________________

   A more common Filipino word for “member” is the Spanish-derived
   miyembro.
