

KASINTAHAN

   root word: [66]sinta

   kasintahan: someone you’re in a romantic relationship with

   magkasintahan: a couple in a romantic relationship

   Magkasintahan sila.
   They are in a romantic relationship.

   Though some may translate the word kasintahan as” lover”, the English
   word has nuances that the Tagalog word does not. The word kasintahan
   sounds very pure and beautiful to Filipinos.
