

KASOSYO

   from the Spanish socio (sapi sa negosyo)

   kasosyo
   business partner

   mga kasosyo
   business partners

   negosyo
   business

   isang kasosyo sa negosyo
   a partner in business

   magkasosyo sa negosyo
   to be partners in business

   Magkasosyo sila.
   They are (business) partners.
     __________________________________________________________________

   karibal
   rival
   (often in romance)

   Magkaribal sila.
   They are rivals.
