

KASTIGO

   This word is from the Spanish
   .

   kas·tí·go
   reprimand, rebuke

   kinastigo
   chastised

   kinastigo
   reprimanded severely

   This word originally meant “punishment” but its meaning has veered
   towards “chastisement.”

MGA KAHULUGAN SA TAGALOG

   kastígo: masidhing pamumuna o pagpuna

   kinastigo: kinagalitan; pinuna nang galit na galit

   pagkastigo: masidhing pagpuna

   ikastígo, kastigúhin, kumastígo, mangastígo
