

KATARUNGAN

   root word: tarong

   katarúngan
   justice

   Katarúngan Para Sa Lahat
   Justice For All

   The Spanish-derived Filipino word is hustísya.

MGA KAHULUGAN SA TAGALOG

   katarúngan: wastong pag-iral ng batas

   katarúngan: pagbibigay ng karapat-dapat na pasiya

   Sa simpleng pangungusap, ang katarungan ay pagbibigay sa tao ng dapat
   ay kanya. Ito ay nababatay sa prinsipyo na ang kayamanan ng mundo ay
   para sa lahat at hindi para sa iilan lamang.
