

KATOK

   katok = tuktok

   katók
   knock

   kumatok
   to knock

   kumatok sa pinto
   to knock on the door

   Sino ang kumakatok?
   Who’s knocking?

   Kumatok ka muna.
   Knock first.

   Kumatok muna bago pumasok.
   Knock before entering.

   May kumakatok.
   There’s someone knocking.

   May kumakatok sa pinto.
   There’s someone knocking on the door.

   may katok sa ulo
   slang for “crazy”
