

KAWALAN

   root word: [66]wala

   kawalan
   loss, a lack of…

   kawalan
   nothingness

   kawalan
   void

   kawaláng-hanggán
   having no end
   = eternity

KAHULUGAN SA TAGALOG

   kawalán: pook o kalagayang walang nabubuhay o umiiral

   kahirapan, kakulangan, kadahupan, karukhaan

   kawaláng-hanggán: pagiging walang-hanggan; pagiging walang katapusan

   kawaláng-hanggán: sa teolohiyang Kristiyano, búhay na walang-hanggan

   kawaláng-hanggán: katotohanang walang kamatayan
