

KAYO

   This is a pronoun.
   kayó
   you (plural)

   ka, ikaw
   you (singular)

   Pangit ka.
   You (one person) are ugly.

   Pangit kayó.
   You (all) are ugly.

   Ikaw ay maganda.
   You are beautiful.

   Kayó ay magaganda.
   You (all) are beautiful.

   kayong lahat
   all of you

   Ingat po kayo.
   Please take care. (to older person)

   Spelling variations for SMS: keo, kyo, kau
