

KILALA

   talastas, alam, batid
   kilala
   to know, recognize a person

   Kilala mo ba si Maria?
   Do you know Mary?

   May kilala ako.
   I know someone.
     __________________________________________________________________

   bantog, tanyag
   kilalá
   known, famous for

   Kilala sila bilang mga prinsesa.
   They are known as princesses.
     __________________________________________________________________

   kilalang-kilala
   very famous

   pagpapakilala
   introduction
