

KILABOT

   kilábot: goosebumps; terror, fear

   kakila-kilabot
   terrifying

   nakakakilabot
   fearsome

   Kinilabutan ako.
   I got goose bumps.

   Nangilabot ako.
   I felt creeped out.

   kilábot sa dunong
   terrifyingly smart

MGA KAHULUGAN SA TAGALOG

   kilabot: pangangalisag ng balahibo, kulag

   kilabot: malaking takot, sindak, kinatatakutan

   kilabot: maninindak, mananakot (karaniwa’y tao, ngunit mayroon ding mga
   pangyayari)
