

KILOS

   galaw, aksiyon, kibo, ibo, akto; ugali, gawi, anyo, asal

   kilos
   act, movement, motion

   kilos
   behavior, conduct, attitude, manner, way

   kumilos
   to act

   di-pagkilos
   inertia, inactivity

   pagkilos
   action

   kilusan
   (political)
   movement

   The Fake Filipino Food Movement
   The Filipino Veterans Equity Movement
   Filipino Americans and the Farm Labor Movement
