

KISLAP

   kinang, ningning, diklap, luningning, kintab

   kislap
   sparkle

   kislap
   scintillation

   kislap
   to glitter, twinkle
     __________________________________________________________________

   kumislap
   glittered, sparkled, twinkled

   kumikislap
   glowing, sparkling, twinkling

   nagkislapan
     __________________________________________________________________

   makislap
   luminous, brilliant, glittering, lambent, lucent
