

KULELAT

   This Tagalog word is slang that is rarely used in formal writing.
   ku·lé·lat
   performs badly

   kulelat
   the very last in a competition

   nangulelat
   ended up last or in the bottom

   kulelat sa mga bansa ng Asya
   the last among the countries of Asia

MGA KAHULUGAN SA TAGALOG

   kulélat: kahulí-hulíhan (ang pinakahulí; ang hulí sa lahat)

   Sa ginanap na paligsahan, isa ang Pilipinas sa mga nangulelat.
