

KULIGLIG

   family Gryllidae

   ku·lig·líg

   kuliglíg
   cricket

   mga kuliglíg
   crickets

   Ang kanta ng mga kuliglig na may tungkuling magbantay sa gabi ang huli
   kong narinig.

   Ay, katahimikang di mabasag-basag maging ng huni ng mga kuliglig sa
   pagtatakipsilim.

MGA KAHULUGAN SA TAGALOG

   kuliglig: kriket, sikada

   kuliglíg: maliit na kulisap na may matinis na sitsit, naririnig kapag
   madilim o kung dumidilim

   kuliglíg: ararong de-mákiná
