

KULÓNG

   napapalibutan, napapaligiran, nababakuran; nakapiit, nakabilanggo,
   napreso, nakakalabos; nakahawla
   kulóng
   jailed, caged

   ikulóng
   to cage, shut in

   kinulong
   caged, jailed

   Kinulong nila ako.
   They locked me up.

   kulungan
   a cage, a prison

   Huwag mo akong kulungin.
   Don’t cage me.

   Ikukulong kita.
   I’ll cage you.

   Ipapakulong kita.
   I’ll have you jailed.

   Ipakukulong kita.
   I’ll have you jailed.
