

   ____________________

Meaning of "kuwitis"

kuwitis •

   n.
     *
          + sky-rocket, fireworks [kwitis]

» synonyms and related words:

   fireworks
   n.
     *
          + rockets, pinwheels, etc: mga paputok, kuwitis [kwitis]

   rocket
   n.
     *
          + a firework that shoots up high in the air and bursts into a
            shower of sparks or stars: kuwitis [kwitis]

   v.
     *
          + to go like a rocket: pumailanglang, sumibad paitaas


