LABAS

   nagsilabasan…
   labás
   outside

   sa labás ng Maynila
   outside Manila
     __________________________________________________________________

   Nasaan ang aso?
   Where is the dog?

   Nasa labás ang aso.
   The dog is outside.
     __________________________________________________________________

   May tao ba sa labás?
   Is there a person outside?

   Walang tao sa labás.
   There’s no one outside.
     __________________________________________________________________

   anak sa labás
   illegitimate child

   mga karapatan ng anak sa labás
   rights of an illegitimate child
     __________________________________________________________________

   Ang kasalungat na salita ng labas ay loob.
   The opposite word of outside in inside.

     __________________________________________________________________

   lumabas
   to come out, emerge

   Lumabas ang katotohanan.
   The truth came out.
     __________________________________________________________________

   palabas sa telebisyon
   television show

   labásan
   exit, a way out
