

   ____________________

Meaning of "lagari"

lagari •

   n.
     *
          + saw

» synonyms and related words:

   saw
   n.
     *
          + a tool for cutting, made of a thin blade with sharp teeth on
            the edge: lagari

   v.
     *
          + 1. to cut with a saw: maglagari, lumagari, lagariin
          + 2. past tense of "see": nakita, nakakita

   handsaw
   n.
     *
          + lagari, surotso


