

LAGA

   pakuluan (sa tubig), pasulakan, iluto
   lagà
   boil

   ilagà
   to boil

   maglaga
   to boil

   Ilaga mo ito.
   Boil this.

   Maglaga ka ng itlog.
   Boil eggs.

   nilaga
   boiled

   nilagang karne
   boiled meat

   nilagang gulay
   boiled vegetables

   The word laga is used when boiling in water a solid mass like eggs or
   meat. When boiling water or liquid, the word is kulo.
   kumukulong tubig
   boiling water
