

LAGI

   parati, palagi, pirme
   lagi
   always, often

   Lagi kang mag-ingat.
   Always be careful.

   Laging ganito.
   Always like this.

   Huwag kang laging ganito.
   Don’t always be like this.
     __________________________________________________________________

   lumagi, v
   to remain

   pamalagiin, v
   to stabilize

   palagian, adj
   regular, steady

   Non-standard spelling (stylized): lageh
