LALAGÚKAN

   root word: lagok

   la·la·gú·kan
   Adam’s apple

   The laryngeal prominence or “neck triangle” is the lump or protrusion
   in the human neck formed by the angle of the thyroid cartilage
   surrounding the larynx seen especially in males.

   Adam's apple in Tagalog Adam's apple in Tagalog

KAHULUGAN SA TAGALOG

   lalagúkan: pag-usli ng kartilago ng thyroid na nabubuo sa may lalamunan
   at karaniwang nakikíta sa mga lalaki
