

LALAMUNAN

   root word: lámon

   lalamúnan
   throat

   lalamunang masakit
   painful throat

   pamamaga ng lalamúnan
   swelling of the throat
   = sore throat

   Namaga ang lalamúnan ko.
   My throat swelled up.

   Makati ang lalamúnan ko.
   My throat is itchy.

KAHULUGAN SA TAGALOG

   lalamúnan: bahagi ng leeg mula sa dakòng loob ng bibig sa ibabâ ng babà
   hanggang sa itaas ng dibdib na kapantay ng balagat

   Ano ang gamot sa makating lalamunan?
