

LAMAN

   karne; katawan; sustansiya, sangkap, materyal; ang bagay na nakasilid,
   kinapapalooban; (patalinhaga) kaupaan, kamunduhan
   laman
   meat, flesh, body, substance

   lamang loob
   innards

   nilalaman
   contents

   walang laman
   “no content” = empty

   malaman
   meaty, substantial

   Anong laman nito?
   What’s contained in here?

   Ano ang nilalaman nito?
   What’s the content of this?
