

LAMBANOG

   Lambalites bottles

   lam·ba·nóg

   lam·ba·nóg
   coconut “wine”

   Lambanog is a potent palm liquor distilled from coconut sap with an
   alcohol content of 40% to 45% by volume. In December 2019, at least 11
   Filipinos died after drinking toxic lambanog.

MGA KAHULUGAN SA TAGALOG

   lambanóg: dinalisay na alak mula sa katas ng sasâ o niyog

   lambanóg: hagupit ng latigo

   lambanóg: saltík
