

   ____________________

Meaning of "lampa"

lampa •

   Ch adj.
     *
          + awkward and unsteady, unsure of footing

» synonyms and related words:

   awkward
   adj.
     *
          + 1. not graceful in movement, clumsy: saliwa, lampa, asiwa
          + 2. not well suited to use: hindi mabuti, hindi akma, hindi
            bagay, hindi angkop
          + 3. not easily managed: mahirap
          + 4. embarrassing: nakahihiya, kahiyahiya
          + 5. inappropriate: alangan


