

LANGOY

   pagkampay o pagkawag ng kamay sa tubig

   langóy
   swimming

   lumangóy
   to swim

   lánguyan
   swimming pool

   lánguyan
   swimming contest

   languyín
   to get by swimming

   languyín
   swim a distance

   Pagdating sa istilo, maaaring lumangoy kasabay ng alon; ngunit kapag
   prinsipyo ang nakataya, maging matatag tulad ng bato.

   “In matters of style, swim with the current; in matters of principle,
   stand like a rock.” — Thomas Jefferson
