

   ____________________

Meaning of "lapit"

lapit •

   adj.
     *
          + malapit (ma-) near, close lumapit (-um-)

   v.
     *
          + to approach or to go near. Lumapit ka sa akin. Come near me.
            maglapit (mag-) to assume positions near to each other.
            Maglapit kayo. Stay close together. maglapit, ilapit (mag-:i-)
            to take something close to someone. Ilapit mo ang silya sa
            kaniya. Move the chair close to him.


