

LASON

   kamandag, beneno; bagay na nakasasama o nakakapipinsala

   lason
   poison

   lasunin
   to poison

   nakakalason
   poisonous

   manlason
   to poison (people)

   manlalason
   poisoner

   Nilason mo ako!
   You poisoned me!

   This also refers to being badly affected by adulterated or contaminated
   food and drink.

   Nalason ang mga bata sa ispageti.
   The kids were “poisoned” by the spaghetti.

   Nalason ako sa kendi.
   I suffered food poisoning from the candy.
