

LIGAYA

   tuwa, luwalhati, galak, lugod, saya, pelisidad, glorya, igaya

   ligaya
   happiness, joy

   magtamong-ligaya
   obtain happiness

   kaliga-ligaya
   ecstatic, very joyful

   kaligayahan
   the state of joy

   kaligayahan ng manok
   chicken’s joy

   lubos na kaligayahan
   utter joy / absolute joy

   naligayahan
   experienced joy

   Walang ligaya sa lupa,
   Na di dinilig ng luha.

   Ligaya is also a woman’s name in the Philippines.
