

LIGTAS

   ang nakasalba, ang natubos
   ligtas
   saved, freed, redeemed

   ligtas
   safe

   Ligtas pa rin sa Ebola ang Pilipinas.
   The Philippines is still safe from Ebola.

   kaligtasan
   the state of being safe

   walang panganib
   no danger

   tagapagligtas
   rescuer / savior
   = superhero
     __________________________________________________________________

   The Filipino word for a safe (strong box) for storing valuables is
   kaha-de-yero.
