

LIMLIM

   This word has at least two different meanings in standard Tagalog
   dictionaries.

   limlim
   body warmth

   limlim
   impending darkness

   lumimlim
   to get darken

   palimliman
   brooder, incubator
     __________________________________________________________________

MGA KAHULUGAN SA TAGALOG

   limlim: halimhim, init ng katawan

   limlim: inkubasyon

   limlim: dapithapon, takipsilim

   nangalimlim
