

LIPAT

   pagtira o pagpunta sa ibang pook; pagsasalin, pagkopya

   lipat
   transfer

   lipat
   move to another place

   Bawal ilipat ang mga upuan.
   It’s prohibited to move the chairs to another place.

                                  ililipat
                       will transfer, move (something)

   Maglilipat kami ng bahay.
   We’re moving houses.
   (We’re moving to a new home.)

   Naglipat sila ng bahay.
   They moved house.
   (They’ve moved to a new home.)
