

LIWANAG

   ilaw, tanglaw, sindi, sinag; kalinawan, klaro
   liwanag, n
   light, shine

   maliwanag, adj
   bright, clear, explicit

   lumiwanag, v
   to clear up, to brighten

   ipaliwanag, v
   to explain, to make clear, to clarify

   [66]paliwanag, n
   explanation

   liwanag sa dilim
   brightness in the dark, light in the darkness

   nagbibigay-liwanag
   luminous

   Liwanag is also a native Tagalog surname of many Filipinos.
