

LUHO

   This word is from the Spanish lujo.

   lúho
   luxury

   luhóso / maluho
   extravagant

   This has a slightly negative connotation.

MGA KAHULUGAN SA TAGALOG

   lúho: anumang bagay na nakadaragdag sa karangyaan ng pamumuhay

   lúho: pagmamalabis sa marangyang pamumuhay, masasarap na pagkain,
   mamaháling pananamit, at katulad

   luhóso / maluho: bulagsak

   Huwag tayong maluho kagaya ng dating administrasyon.
