

LUHOD

   pagtitikop ng dalawang tuhod habang nagdarasal
   luhod
   kneel

   lumuhod
   knelt

   Luhod!
   Kneel down!

   Hala! Luhod!
   Go ahead, kneel!

   Lumuhod ka!
   You kneel!

   Lumuhod ka sa harapan ko.
   Kneel in front of me.

   Lumuhod ako sa harapan niya.
   I knelt in front of him/her.

   Ayaw kong lumuhod.
   I don’t want to kneel.

   Hindi ko kayang lumuhod. Masakit ang tuhod ko.
   I’m unable to kneel. My knees hurt.
