

LUPIT

   bagsik, bangis, kahayupan
   lupit
   cruelty, mercilessness

   lupit
   savageness, harshness

   [66]malupit
   cruel, brutal

   pagmamalupit
   abuse, harsh treatment

   Ang lupit mo.
   You’re so cruel.

   Hindi ko natiis ang kanyang pagmamalupit.
   I couldn’t bear his/her harsh treatment.

   Masakit pagmalupitan ng babae.
   It hurts to be treated harshly by a woman.

   Misspelling: lupet
