MABANGIS

   root word: bangís
   mabangis
   savage, vicious, fierce, ferocious

   mabangis na hayop
   wild, ferocious animal

   mabangis na tingin
   fierce look

   mabangis na kamay
   savage hand

   Nakakatakot ang bangis ng hayop.
   The animal’s fierceness/ferocity is frightening.

   Ang kasalungat na salita ng mabangis ay maamo.
   The opposite word of wild (fierce) is tame (gentle).

KAHULUGAN SA TAGALOG

   mabangis: malahayop na bagsik
