

MADULAS

   root word: dulás

   madulás
   slippery

   madulás
   to slip

   nadulás
   slipped

MGA KAHULUGAN SA TAGALOG

   madulás: may katangian ng dulás

   madulás: mahirap mahúli

   dulás: kadalian ng pagdaraan sa ibabaw ng isang bagay na makinis at
   tíla may langis

   dulás: pagdausdos nang bigla o hindi sinasadyang pagkabuwal at
   pagkawala ng panimbang

   dulás: kilos o pangyayaring tuloy-tuloy, maginhawa, at wasto
