

MAGITING

   root word: gíting (meaning: heroism)

   ma·gí·ting
   heroic

   magiting
   brave

   Pinagkalooban mo ang aming lalawigan ng maraming mga magigiting na mga
   bayaning nabuwal sa dilim ng gabi noong panahon ng himagsikan.
   Alalahanin mo sila at pagkalooban mo ng ginhawa, liwanag at kapayapaan.

MGA KAHULUGAN SA TAGALOG

   magíting: may angking gítin

   gíting: kabayaníhan

   gíting: lakas ng loob at matibay na kapasiyahang humarap sa panganib at
   kamatayan
