

MAHALAGA

   root word: halaga (meaning: value)
   mahalaga
   important

   Mahalaga ka sa akin.
   You are important to me.

   Mahalaga ito.
   This is important.

   mahalagang pag-uusap
   important conversation

   mahahalagang bagay
   important things

   Alin ang higit na mahalaga?
   Which is more important?

   The Spanish-derived Tagalog word for ‘important’ is importante.
   Importanteng gawin mo ito.
   It’s important that you do this.
