

MAHINAHON

   root word: hináhon

   ma·hi·ná·hon
   calm, moderate,
   sober

   possessing equilibrium or equanimity, not wild or driven by emotion

   mahinahong pananakop
   calm occupation
   (as by a military force)

   mahinahong pananakop
   “benevolent assimilation”

MGA KAHULUGAN SA TAGALOG

   mahináhon: may angking hinahon

   hináhon: panatag na kalooban

   hináhon: katangiang hindi madalîng malito o magambala
