

MAIKLI

   root word: ikli
   ma·ik·lî
   short, brief

   mas maikli
   shorter

   maikling kuwento
   short story

   mga maiikling kuwento
   short stories

   Variation: maigsi
   Ang kasalungat ng salitang maikli ay mahaba.
   The opposite of the word short is long.

   Synonym: maigsi
     __________________________________________________________________

KAHULUGAN SA TAGALOG

   maiklî: may katangian ng ikli
