

MAINAM

   root word: inam
   inam
   niceness, neatness, goodness

   inam ng kilos
   gentility/elegance of behavior

   Ang inam ng kilos!
   How elegant the bearing!

   mainam
   respectable, temperate, modest

   pinaka-mainam
   best, prime, first-rate

   Alin dito ang pinakamainam?
   Which of these is the best?

   pinainam
   to have made something good or better

   kainaman
   sufficient quantity, mildness
