

MAKITA

   root word: kíta

   makita
   to be able to see

   Gusto kitang makita.
   I want to see you.

   Sana makita kita.
   I hope I’ll be able to see you.

   Sana makita mo ako.
   Hope you’ll be able to see me.

   Sana makita mo ang mundo ko.
   I wish you could see my world.

   Shorthand spelling variations: mkita, mkta
     __________________________________________________________________

   Another meaning for the word kíta could refer to income.
