

MALA-

   This is a prefix expressing similarity.

   It can be translated as “somewhat” or “semi-“.

   mala-kolonyal
   somewhat colonial

   mala-anghel
   like an angel

   malasutla
   silken
   “like silk”

   malasutlang dagat
   silken sea/ocean

   malasutlang kutis
   silken skin complexion
   = very smooth and soft skin

   Sa balarila, ito ay pambuo ng pang-uri na nangangahulugang kawangis o
   katulad.
