

MALAMANG

   root word: lamang
   malamang
   probably, likely

   Malamang sirena.
   It’s likely a mermaid.
     __________________________________________________________________

   Related Tagalog words: baka, siguro
   Baka sirena.
   Maybe it’s a mermaid.

   Siguro sirena.
   It’s probably a mermaid.
     __________________________________________________________________

   Separate from above, there is the word malaman (to know), which has
   the inflected form malamang.
