

MALAMBOT

   root word: [66]lambót

   ma·lam·bót
   soft, tender

   Malambot ang unan.
   The pillow is soft.

   Malambot ang kamay ng babae.
   The woman’s hand is soft.

   Malambot ito.
   This is soft.

   Malalambot ang mga ito.
   These are soft.

   Ang kasalungat ng malambot ay matigas.
   The opposite of soft is hard.

   malalambot na labi
   soft lips

KAHULUGAN SA TAGALOG

   malambót: may katangian ng lambot
