

MALETA

   from the Spanish maleta, meaning “valise” (suitcase)
   maleta
   suitcase, luggage

   mga maleta
   suitcases

   Nasaan ang maleta ko?
   Where’s my suitcase?

   Nasaan ang mga maleta ko?
   Where are my suitcase?

   Hindi ko alam kung nasaan ang maleta ko.
   I don’t know where my suitcase is.

   Nawala yata ang maleta mo.
   I think your suitcase got lost.

   Related Filipino word: bagahe (luggage)
