

MAMA

   At least three different meanings for this word.

   mamá
   mother

   Maagang nagising [66]si Mama.
   Mom woke up early.
     __________________________________________________________________

   mamà
   term of address for an unknown man

   [67]Mamang Sorbetero
   Mr. Ice-Cream Man
     __________________________________________________________________

   mamâ
   to chew betel leaves
