

MANEHO

   This word is from the Spanish manejar.

   maneho
   drive

   Marunong ka bang magmaneho?
   Do you know how to drive?

   Hindi ako marunong mag-maneho.
   I don’t know how to drive.

   Sino ang magmamaneho?
   Who will drive?

   Ang drayber.
   The driver.

   Kaya kong magmaneho ng trak.
   I am able to drive a truck.

   Hindi ko kayang magmaneho ng trak.
   I don’t have the ability to drive a truck.
