MARIKIT

   This is an old-fashioned word for “pretty.”

   marikit
   dainty

   pinarikit
   made pretty

   isang marikit na larawan
   a pretty picture

                                 pamparikit
                              for making pretty

   Old spelling variation: mariquit

   An old love song has the title Bituing Marikit (Beautiful Star).

   The commonly used word for “beautiful” these days is maganda.

KAHULUGAN SA TAGALOG

   ma·ri·kít: may katangi-tanging dilag o pang-akit
