

MASAYA

   Be Happy in Tagalog Be Happy in Tagalog

   Maging Masaya 🙂
   Be Happy!
     __________________________________________________________________

   masayá
   happy

   masayá
   glad

   masayang-masaya
   very happy

   Masayá ako.
   I’m happy.

   Masayá para sa iyo.
   Happy for you.

   Masayá ako para sa iyo.
   I’m happy for you.

   Masayá ka ba?
   Are you happy?

   Masayá ka ba sa kanya?
   Are you happy with him/her?

   Mas marami, mas masayá…
   The  more, the merrier…

   masayahin
   cheerful
     __________________________________________________________________

   In greetings, the equivalent of the English “Happy…” is usually
   “Maligayang…” in Tagalog.
   Maligayang Kaarawan!
   Happy Birthday!
     __________________________________________________________________

   Ang kasalungat ng salitang masaya ay malungkot.
   The opposite of the word happy is sad.
     __________________________________________________________________

   Shorthand variation in SMS texts and chat: msya
