

MASAKIT

   root word: [66]sakit
   masakit
   hurts

   masakit
   painful, sore

   Saan masakit?
   Where does it hurt?

   Masakit ang paa ko.
   My foot hurts.

   Masakit ang tiyan ko.
   My tummy hurts.

   Masakit ang lalamuman ko.
   My throat hurts.

   Masakit ang puwit niya.
   His/Her butt hurts.

   Masakit umibig.
   It hurts to love.

   Masakit ang puso ko.
   My heart hurts.

   Masakit ang dibdib ni Lola.
   Grandma’s chest hurts.
