

MASYADO

   often pronounced as “mashado”

   This word is from the Spanish demasiado.
   masyádo
   excessive, too much

   masyadong puno
   too full, overloaded

   masyadong matagal
   takes too long

   masyadong seryoso
   too serious

   Hindi na masyadong mainit.
   It’s no longer that hot.

   Masyado ka na.
   You’re too much already.
   (You’re overdoing it.
   You’ve gone overboard.)

   The native Tagalog equivalent is labis.
