

MATABANG

   root word: tabáng

   matabáng
   insipid, lacking taste

   Matabang ito. Dagdagan mo ng asin.
   This barely has any taste. Add salt.

   Ang kasalungat ng matabang ay malasa.
   The opposite of flavorless is flavorful.

   tabangan
   make less salty
     __________________________________________________________________

   Unrelated to the above, the word is also the conjugated form of mataba.
   mataba
   fat

   matabang baboy
   fat pig
