

MATATAG

   root word: tatág

   matatág
   immovable

   matatag
   uncompromising

   matatag
   firm, sturdy

   Lakad Matatag, Normalin Normalin
   Steady Walk, Attack Per Normal

   Subok na Matibay, Subok na Matatag was the very well-known slogan of
   Banco Filipino, a famous Philippine savings and loan association, which
   ironically went out of business in 2011 due to excessive liabilities.

   Kahulugan sa Tagalog: mahirap galawin o ibuwal, matibay, lapat
