

MATINIK

   root word: [66]tinik
   tinik
   thorn

   tinik
   fishbone
     __________________________________________________________________

   matinik
   thorny

   Matinik ang halaman.
   The plant is thorny.
     __________________________________________________________________

   matinik
   bony

   Matinik ang isda.
   The fish is bony.
     __________________________________________________________________

   Natinik ako sa rosas.
   I was wounded by the rose’s thorn.

   Natinik ako habang kumakain.
   A fishbone got caught in my throat while I was eating.
