

MATINDI

   root word: tindi (intensity, severity)

   matindi
   intense, severe, extreme

   matinding sakit
   intense pain

   matinding selos
   intense jealousy

   matinding “istres”
   extreme stress

   intensibo
   intensive

   Matindi ang away.
   The fight is intense.

   Matindi ang ensayo.
   The practice is intense.

   matinding-matindi
   very severe

   Related colloquial words for ‘intense’
   grabe, sobra
