

   ____________________

Meaning of "mongha"

mongha •

   n.
     *
          + nun

» synonyms and related words:

   nun
   n.
     *
          + 1. a woman belonging to a religious congregation: madre
          + 2. a contemplative nun: mongha

   sister
   n.
     *
          + 1. kapatid na babae
          + 2. any elder sister or the eldest: ate, manang
          + 3. the second eldest sister: ditse
          + 4. a nun: madre, mongha


