

MULTÓ

   ghost in Tagalog

   This word is from the Spanish muerto (meaning: “dead”).
   multó
   ghost

   May multó sa bahay.
   There’s a ghost in the house.

   mga kwentong multo
   ghost stories

   Mga Kwentong Katatakutan
   Horror Stories

   pinagmumultuhan
   is haunted

   May nagmumulto dito.
   There’s something haunting this place.

   Filipino children use the cuter word [66]mumò.
