

MUNTÎ

   This can be considered a classical Tagalog word for “small” — as quaint
   as the use of “little” in English these days.

   The more widely used contemporary adjective used for “small” is maliit.

   muntî
   little

   Tatlong Munting Baboy
   Three Little Pigs

   Mumunting Dalaga
   Little Women
   (Louisa May Alcott)

   Ako’y Munting Tinig…
   I Am But A Small Voice…
   (song lyrics by Odina Batnag)
