

NAIS

   gusto, pita, hangad, nasa, adhika, pakay, mithi, lunggati; ambisyon,
   pangarap, panaginip; tunguhin, puntahin
    nais
   desire, wish

   naisin
   wish for, desire

   pagnanais
   desiring, preference, wishing

   kanais-nais
   desirable

   Nais kong lumipad.
   I wish to fly.

   Nais kong makasama ka.
   I want to be with you.

   Ang nais ko ay…
   What I want is…

   Ang nais ko ay makasama ka.
   What I want is to be with you.

   magnais, nagnanais, nagnais, magnanais
