

NAKA-

   This is not a standalone word, but a prefix.
     __________________________________________________________________

   1. forms adjectives that denotes possession
   nakahikaw
   wearing earrings

   nakapalda
   wearing a skirt
     __________________________________________________________________

   2. may indicate temporary states
   nakabukas
   is open

   nakaluyloy
   hanging
     __________________________________________________________________

   3. may form causative adjectives
   nakamamatay
   can cause death, is fatal

   nakauuhaw
   causing thirst
