

NANLOOB

   root word: [66]loób (meaning: inside)

   nanloób
   entered

   nanloob
   went inside

   Ang tulisan ay nanloob sa isang bangko.
   The bandit entered a bank.

   This has a connotation that the entry is undesirable or prohibited. It
   has been used when an evil spirit enters a human body or when an
   invading force takes over a town.

KAHULUGAN SA TAGALOG

   nanloob: pumasok sa loob

   Ang masasamang espiritu ay pumasok at nanloob sa mga tao.
