

NAPAKA-

   This is a prefix.

   napaka-
   so very
     __________________________________________________________________

   buti
   good

   napakabuti
   so very good
     __________________________________________________________________

   sarap
   delicious

   napakasarap
   so very delicious
     __________________________________________________________________

   tamad
   lazy

   napakatamad
   so very lazy
     __________________________________________________________________

   Recently, napaka- is being shortened to ka– in conversation and texts.

   Nakakagutom.
   Makes one hungry.

   Kagutom.
   Is making one hungry.
