

NATALOS

   root word: talós

KAHULUGAN SA TAGALOG

   talos: alam, batid

   talos: nauunawaan, naiintidihan, natatanto

   natalos: nalaman, nabatid

   natalos: naunawaan, naintidihan, natanto

   natatalos: nauunawaan, naiintidihan, natatanto

   matatalos: mauunawaan, maiintidihan, matatanto

   nakatalos: nakaunawa

   Hindi lamang natin natatalos ito sapagka’t tayo ay nalulunod sa malabis
   na pagpapahalaga sa sarili.
