

   ____________________

Meaning of "ng"

ng •

   mkr.
     *
          + non-focus marking particle of actor or goal complements or
            noun phrases. Kinain ng bata ang kendi. The child ate the
            candy. part. possessive marker, common noun marker which marks
            a possessive construction. Direktor ng sine. Director of the
            movie -ng lig. variant of na nga' adv. affirmative adverb
            "indeed". Siya nga ang duwag. He is indeed the coward.


