

NGILO

   ngiló: tingling sensation in the teeth

   mangiló: to feel a tingling sensation in the teeth

   mangiló: to have a nerve pain in the teeth

   nagpapangilo: caused one to have a tingling sensation in the teeth

   pangingilo ng mga ngipin: “sensitivity of teeth”

KAHULUGAN SA TAGALOG

   nangilo: nangimay ang ngipin dahil sa asim ng kinakain o iniinom o
   dahil sa gigil na tunog, atbp

   pangingilo: pakiramdam ng ngiló
