

NINAKAW

   root word: nakaw
   ninakaw
   stole

   Ninakaw mo ito sa akin.
   You stole this from me.

   Ninakaw nila ito sa akin.
   They stole this from me.

   Ninakaw ito ng mga baboy.
   The pigs stole this.

   Ninakaw ito.
   This is stolen

   Ninakawan ako.
   I was stolen from.

   Ninakaw mo ang puso ko.
   You stole my heart.

   Ninakaw daw ng kumpanyang ‘yan ang marka ng San Miguel.
   They say that company stole San Miguel’s mark.
