

   ____________________

Meaning of "nino"

nino •

   pron.
     *
          + whose, post positive form of kanino. Kaninong bahay, bahay
            nino. Whose house.

» synonyms and related words:

   whose
   pron.
     *
          + 1. of whom, of which: rendered by the ligature "na" and its
            variant "-ng"
          + 2. an interrogative, meaning "to whom": kanino (prepositive),
            nino (postpositive)


