

   ____________________

Meaning of "pa"

pa •

   af. affix
     *
          + for verbs meaning "to cause, get or allow someone to do what
            the root word indicate" pa adv. more, yet, still (expresses
            the immaturity or continuance of a situation and stands in
            contrast with na). Mabuti pa. Better yet. Basa pa ang damit.
            The clothes are still wet.


