

PAALAM

   paalam = farewell ([66]goodbye)

   Mamamaalam na ako.
   I’m bidding farewell now.
     __________________________________________________________________

MGA KAHULUGAN SA TAGALOG

   paalam: bigkas ng umaalis sa nililisan

   paalam: adyos

   paalam: pahimakas
     __________________________________________________________________

   Mga ilang oras pa, mamamaalam na naman ang araw sa kanluran.

   Mamamaalam siya nguni’t mananatili ang maraming magigiting na alaala.
