

PAGITAN

   pagitan: intervening space

   pagitan: aisle; interval

   mamagitan: interpose, interfere, arbitrate

   sa pagitan ng: midway, midway

   sa pamamagitan ng: by means of of, through, upon

   tagapamagitan: mediator, intermediary; go-between
     __________________________________________________________________

KAHULUGAN SA TAGALOG

   pagitan: puwang o agwat sa dalawang bagay

   pagitan: puwang, espasyo, interbalo

   pagitan: agwat, layo, awang

   pagitan: patlang
