

PAGSIKLAB

   root word: sikláb (meaning: blaze)

   pagsikláb
   blazing, outbreak

   ang pagsiklab ng digmaan
   the outbreak of war

MGA KAHULUGAN SA TAGALOG

   pagsiklab: pagliyab

   pagsiklab: biglaan at matinding paglaki ng apoy

   Binabantayan ang maaaring pagsiklab ng digmaang nukleyar.

   Sa pagsiklab ng digmaan noong 1896, kasama siya sa unang sagupaan ng
   mga Katipunero at mga Kastila.
