

PAHIYAS

   root word: hiyás

   Pahiyás is the name of a Philippine festival in Quezon celebrated
   every year on the 15th of May

MGA KAHULUGAN SA TAGALOG

   pahiyás: tumutukoy sa hiyás na ibinigay o ipinagamit sa isang tao

   pahiyás: mamahálin at magagandang palamuti

   Pahiyás: pistang bayan sa Quezon na ipinagdiriwang sa pamamagitan
   ng pagsasabit ng makukulay na kiping sa dingding o bintana ng bahay
   bílang pasasalamat kay San Isidro de Labrador tuwing ika-15 ng Mayo
