

PAKAININ

   root word: [66]kain

   pakainin
   to feed

   Pakainin mo ang bata.
   Feed the child.

   Pakainin mo na ang baboy.
   Feed the pig already.

   Pakainin mo na ang mga baboy.
   Feed the pigs already.

   napakain ng laway
   was able to feed someone spit or saliva
   = was able to persuade someone to do something

   Ano ang pinapakain mo sa kanila?
   What are you feeding them?

   Pinapakain ko sila ng tinapay.
   I feed them bread.
