

PAKIALAM

   root word: [66]alam

   pakialam
   to give a care

   Wala akong pakialam.
   I don’t care.

   Wala akong pake.
   I don’t give a sh*t.
     __________________________________________________________________

   Anong pakialam ko sa kanila?
   What do I care about them??
   = I don’t give a rat’s fck about them.

   Minsan mabuti pang magkunwari na wala kang pakialam. Sometimes it’s
   better to pretend that you don’t care.
