

PALAYAW

   root word: layaw

   pa·lá·yaw
   nickname, sobriquet

   Ano ang palayaw mo?
   What is your nickname?

   Anong palayaw mo?
   What’s your nickname?

   Guwapo ang palayaw ko.
   Handsome is my nickname.

KAHULUGAN SA TAGALOG

   paláyaw: pangalang idinaragdag o inihahalili sa tunay na pangalan ng
   isang tao, pook, at iba pa

   bansag, tawag, taguri, alyas; pangalan

   magpaláyaw, palayáwan, ipaláyaw
