

PALAPAG

   floor, storey

   ikalawang palapág
   second floor
     __________________________________________________________________

MGA KAHULUGAN SA TAGALOG

   palapág: dibisyon o pahalang na pagkakahatì ng bahay o gusali mula
   pundasyon paitaas hanggang bubong

   palapág: silong ng bahay ng mga táong may káya sa búhay
     __________________________________________________________________

   palapág: papunta sa ibabâ
     __________________________________________________________________

   pálapágan: paliparan
