

PALARIN

   root word: palad

   palarin
   be lucky

   palarin
   happen to have the good fortune

   Sana pagpalarin ka.
   Hope good fortune shines on you.
   = May you have good luck.

   palarin
   “prosper”

   Palarin was the name of a startup that launched in 2015 with the aim of
   bringing easy bitcoin access to the Philippines.

   Our bitcoin address for donations: 1A4UR9RKDc41xNvaLG4Lngi48TCJFt67Hc

   BCH (Bitcoin Cash): 18NX9b5KLQksoYWMbN9rARwuihSCEosSeW
