

PALAGI

   root word: lagi

   palagi
   always, often

   Palagi kitang iniisip.
   I always think of you.

   Palaging natutulog ang bata.
   The child always sleeps.

   Palaging may pag-ibig.
   There’s always love.

   Palaging may pag-asa.
   There’s always hope.

   Palaging may bago dito.
   There’s always something new here.

   Palaging may nagmamahal sa iyo.
   There’s always someone who loves you.
