

PAMANGKIN

   anak ng kapatid o pinsan
   pamangkin
   niece or nephew

   mga pamangkin
   nieces /nephews

   pamangking babae
   niece

   pamangking lalaki
   nephew

   pamangkin ko
   my niece/nephew

   ang aking pamangkin
   my niece/nephew

   ang pamangkin mo
   your niece/nephew

   ang iyong pamangkin
   your niece/nephew

KAHULUGAN SA TAGALOG

   pamangkín: anak ng kapatid, pinsan, o ng asawang kauli
