

PANGGAP

   kunwari, kunwa, kunyari
   panggáp, magpanggáp
   to pretend, to profess

   nagpanggap
   pretended to be

   Nagpanggap na matalino.
   Pretended to be smart.

   nagpapanggap
   is pretending to be

   Nagpapanggap akong babae.
   I’m pretending to be a woman.

   Sige, magpanggap ka lang na masaya ka. Tutal, diyan ka naman magaling.
   Go ahead and pretend you’re happy. Anyway, that’s what you’re good at.
