

PANIKI

   bats in Tagalog

   Sa soolohiya, malaking kabag-kabag.

   paniki
   fruit bat

   mga paniki
   bats

   paniking itim
   black bat

   mga paniking itim
   black bats

   itim na paniki
   black pat

   mga itim na paniki
   black bats

   paniking lumilipad
   flying bat

   mga paniking lumilipad
   flying bats

   lumilipad na paniki
   flying bat

   mga lumilipad na paniki
   flying bats
