

PANTAY

   pareho, magkasintaas, kasintaas; magkasimbaba, simbaba; patag, nibelado

   pantay
   even, equal, level

   kapantay
   level, equal

   walang-kapantay
   having no equal, unparalleled

   walang kapantay
   incomparable

   magkapantay
   on the same level

   pantay
   flat, smooth

   pantayin
   to even off, to make level

   pantay-pantayin
   to make everything equal

   pamantayan
   standard, average, norm

   Ano ang “hindi pantay” in English? Uneven.
