

PANTALAN

   This word is reportedly from the Spanish language.

   pán·ta·lán
   pier

   pantalán
   wooden / can quay

   Mahigpit ang seguridad sa mga pantalan.
   Security is tight at the piers.
     __________________________________________________________________

MGA KAHULUGAN SA TAGALOG

   pántalán: piyér, lunsaran, daungan, bunsuran, bantilan

   Katulad ng pagkalunod ng mga bituin sa dilim, ang sisinghap-singhap na
   kaluluwa ay humahanap ng pantalan.
