

PANUTÓ

   root word: tūto

   pa·nu·tó
   indicator

   panutó
   instruction, order

   mga panutó
   instructions

MGA KAHULUGAN SA TAGALOG

   panutó: paglangoy nang nakatingala

   panúto: moral o espiritwal na patnubay

   panúto: panturò

   panúto: paghanap o pagtunton sa dulo ng isang bagay

   Sundan nang wasto sa mga panutong nakalimbag.

   May panutong nagbibigay ng direksyon ng hinahanap na opisina, gusali o
   tirahan.

   Kailangan bang sundin ang mga panuto ?
