

PAPUTOK

   root word: putók
   pa·pu·tók
   firecrackers, fireworks

   iligal na paputok
   illegal fireworks

   paputok sa Bagong Taon
   firecrackers in the New Year

   pabrika ng paputok
   fireworks factory

   magpaputok
   to detonate, explode

   saludong paputok
   gun salute

   paputok sa ika-4 ng Hulyo
   fireworks on the 4th of July

   misspelling: papotok

KAHULUGAN SA TAGALOG

   paputók: rebentador at iba pang laruang pinasasabog kung may
   pagdiriwang

   fireworks in Tagalog fireworks in Tagalog
