

PARADAHAN

   root word: parada, from the Spanish parar

   paradahan
   parking lot

   paradahan
   a place to park

   paradahan ng bus
   bus stop

   paradahan ng mg dyipni
   where jeepneys park
     __________________________________________________________________

   ipinarada
   parked, paraded

   pinarada ang mga sasakyan
   parked the vehicles

   ipinarada ang mga bata sa kalye
   paraded the kids in the street
