

PARATI

   root word: dati

   parati
   always

   parating naka-on
   always on

   laging naka-on
   always on

   palaging naka-on
   always on

   Parati ka nandito.
   You’re always here.

   Lagi ka nandito.
   You’re always here.

   Palagi ka nandito.
   You’re always here.
     __________________________________________________________________

   páratihán
   permanent
   (not common usage)

   Permanente ito.
   This is permament.
