

   ____________________

Meaning of "paratang"

paratang •

   n.
     *
          + accusation

» synonyms and related words:

   acusation
   n.
     *
          + a charge of some offence: paratang, bintang

   complaint
   n.
     *
          + 1. complaint: daing
          + 2. finding fault: reklamo, sumbong
          + 3. accusation: paratang
          + 4. a formal accusation: sakdal, demanda, habla
          + 5. expression of pain, grief, etc.: daing, hinaing


