

PASADO

   This word is from the Spanish language.

   pasado
   past

   pasado alas dose
   past twelve o’clock

   pasado alas kuwatro
   past four o’clock

   “Masipag na bata iyang si Pedro… pero mahina sa klase,” sabi ni Gng.
   Cruz. “Hindi ko siya mabibigyan ng pasadong marka.”

   “Peter is a hardworking student… but weak in class,” said Mrs. Cruz. “I
   can’t give him a passing grade.”

MGA KAHULUGAN SA TAGALOG

   pasado: lipás, nakaraan
