

   ____________________

Meaning of "pasok"

pasok •

   v.
     *
          + pumasok, pasukin (um-:-in) to go to work, to go to school, to
            enter. Pumasok ka sa kuwarto ng ate mo. Enter your elder
            sister's room. magpasok, ipasok (mag-: i-)

   v.
     *
          + to enter, to go inside, to insert, to deposit (money). Ipasok
            mo ang mga plinantsa sa silid. Put the things you ironed into
            the room.


