

PATA

   This word is from the Spanish language.

   pata: binti ng hayop (leg of animal)

   krispy pata krispy pata

   There’s a popular Filipino dish called “crispy pata,” which is pigs’
   hocks that are boiled and then deep-fried.
   krispy pata krispy pata Crispy Pata
     __________________________________________________________________

   Unrelated to the above, and more obscure:

   patâ: fatigued, exhausted

   pagod, lata, panlalambot, pagal; hingal, lawit ang dila sa hirap
