

PATO

   This word is from the Spanish language.
   páto
   white duck

   ang páto
   the duck

   mga páto
   ducks

   itlog ng páto
   duck egg

   tuka ng páto
   duck’s beak

   pakpak ng páto
   duck’s wing

   Naglakad ang páto.
   The duck walked.

   Malinis ang páto.
   The duck is clean.
     __________________________________________________________________

   itik
   small, brown duck

   bibi / bibe
   duckling

   lákad-páto: mumunting hakbang na may paggiwang ng balakang
