

PAYAG

   sang-ayon; alinsunod, ayon, tulot

   payag
   agreement

   payag
   consent

   pumayag
   agreed, consented

   Pinayagan ako ng mga magulang ko.
   My parents gave me their consent.
   = My parents allowed me.
   = They gave me their ok.

   Ayaw akong payagan.
   (They) don’t want to give me their ok.

   Ayaw nila akong payagan.
   They don’t want to give me their ok.

   Napapayag ko sila.
   I was able to convince them to consent.
