

PAYAT

   impis ang katawan; hilahod, butu’t balat, payatot; labas ang parilya

   payat
   thin, slender

   payatot
   skinny

   mamayat
   to become thin

   nangayayat
   became thin

   namayat
   to grow thin

   Namayat siya.
   He/She grew thin.

   pumayat
   became thin

   Pumayat ka!
   You’ve become thin!
   = You’ve lost weight.

   payat at mataba
   thin and fat

   Ang kasalungat ng payat ay mataba.
   The opposite of thin is fat.
