

PAYAPA

   panatag, tiwasay, tahimik
   payapa
   peaceful, tranquil, placid

   Ang gabi’y payapa.
   The night is peaceful.
     __________________________________________________________________

   kapayapaan
   peace, tranquility

   kapayapaan sa mundo
   world peace
     __________________________________________________________________

   Mamayapa nawa ang kaluluwa ni Michael Jackson.
   May Michael Jackson’s soul rest in peace.
     __________________________________________________________________

   mapayapa
   peaceful

   Hindi pa rin mapayapa ang aking isipan.
   My mind is still not at peace.
     __________________________________________________________________

   payapain
   to pacify, to make peaceful

   Kaya ng Diyos payapain ang dagat.
   God can calm the ocean.
     __________________________________________________________________

   mga inosenteng tao na walang ibang hinangad kundi ang mabuhay nang
   payapa innocent people who wished for nothing other than to live
   peacefully
