

   ____________________

Meaning of "payong"

payong •

   n.
     *
          + umbrella

» synonyms and related words:

   umbrella
   n.
     *
          + payong

   sukob
   v.
     *
          + sumukob (-um-) to share a cover or shelter (e.g. umbrella).
            Sumukob si Rosita sa payong ko. Rosita shared my umbrella.
            magsukob, isukob (mag-:i-)

   v.
     *
          + Isukob mo ang bata sa payong mo. Let the child share your
            umbrella.


