

   IFRAME:
   https://www.fiverr.com/embed_gigs?id=U2FsdGVkX1+CFUvPA6U6f9Q8B066qG
   3SoJUc4gasZRoKeniO9FhK/9jXOeYNRzwGINh7+BcRfPMXTYsa6SZt5uMl6Cd78wxViy6B+
   fWQUXlKigdvwlEibD5PvkDswNFQft2m0bvcmyOq3C/nYwjdOTfz8dxhGoBQyuKPIYJI56QU
   NGp5VLoP+FpcDrAAxbjKQlgHumN7HWodk2+WIYAwWmIW+b9JPd4Tj7M+88f/HFmwGLlHYs4
   kWe+U0dxrRop9IwsuzdIkrTByn1BFtHO7bhj9zCA9LEeeAionVFqSAnYEmlrOF+ajb1jZ+j
   Fr/6YS1MoPpKeW/k1Fti/rKbos1mC4S0UpyYYng949let9RH0t/aYmtP16J6DtD4mJn67Rp
   TMu6IBtQvJTxGlKYEPHzDSeHKLGr4EpmL2tWTV0AL0itlvXgJypJUb3QQQvJFpkAyLh8+ei
   6MhvtR0SsbffhBPnx58TVML0UMIMR4TUZvO7rKJxIgdFJqru26DTN8iE&affiliate_id=3
   487&strip_google_tagmanager=true

PINITAK

   pitak: paddy

   pitak sa lupa: croft

   munting bukid: croft

   A croft is a small rented farm, especially one in Scotland, comprising
   a plot of arable land attached to a house and with a right of pasturage
   held in common with other such farms.

   pinitak: a row of farmland
     __________________________________________________________________

   Nang naglilipat sila ng punla noong isang taon ay maghapong nakababad
   siya sa putik ng pinitak maulanan at maarawan.

   Last year when they were transplanting seedlings, she was soaked in the
   mud of the rice paddy and was exposed to the sund and the rain.

   buong pinitak, tubig sa pinitak…

   Wala nang isda sa mga pinitak at sangka dahil sa mga nakalalasong
   kemikal na pansakahan.

   “Nakapagpagawa na kami ng kanal na patuyuan ng tubig buhat sa mga
   pinitak hanggang sa pinak.”
     __________________________________________________________________

   Araro ang gintong plumang sa lupa’y isinusulat,
   Bawat salitang matitik sa pinitak ang sambulat

   The golden plume writing on the land is a plow
   Each written word, what is scattered in the rows
     __________________________________________________________________

   Mayroon nang isang dipa na kanyang naararo sa mga unang pinitak ng
   kanyang saka.
     __________________________________________________________________

   “Nakapagpagawa na kami ng kanal na patuyuan ng tubig buhat sa mga
   pinitak hanggang sa pinak,” wika ni Kapitan. Ang mga isda raw sa pinak,
   tulad ng dalag, hito…
