

PINTO

   halang na naisasara at naibubukas
   pintô
   door

   pintuan
   doorway
     __________________________________________________________________

   Another meaning of the word pinto can be seen in conjugated form.
   namiminto
   on the threshold

   namiminto
   likely to happen soon

   namiminto
   expected to happen

   also spelled as napipinto

   napipinto
   imminent, impending,
   approaching, pending, upcoming

   Tagalog synonyms: nalalapit, darating
