

PISI

   twine (strong thread or string consisting of two or more strands of
   hemp, cotton, or nylon twisted together)

MGA KAHULUGAN SA TAGALOG

   pisi: tali, leteng, lubid, panali

   mahaba ang pisi: mahaba ang pasensya

MGA KAHULUGAN SA TAGALOG

   pisì: sinulid na yari sa bulak

   pisì: paraan ng pag-uri sa habà o ikli ng pasensiya, o sa dami ng
   salapi gaya sa “maikli ang pisì” o “mahabà ang pisì”
