

PITO

   At least two meanings for this word in the dictionary, differentiated
   by accented syllable.

   pitó
   seven (7)

   labimpitó
   seventeen

   makapitó
   seven times

   pipitó
   only seven
     __________________________________________________________________

    from the Spanish
   pito
   whistle, flute

   pumito
   to whistle, whistled

   Paano Pumito
   How to Whistle

   Pipito ako.
   I will whistle.
