

   IFRAME:
   https://www.fiverr.com/embed_gigs?id=U2FsdGVkX1+CFUvPA6U6f9Q8B066qG
   3SoJUc4gasZRoKeniO9FhK/9jXOeYNRzwGINh7+BcRfPMXTYsa6SZt5uMl6Cd78wxViy6B+
   fWQUXlKigdvwlEibD5PvkDswNFQft2m0bvcmyOq3C/nYwjdOTfz8dxhGoBQyuKPIYJI56QU
   NGp5VLoP+FpcDrAAxbjKQlgHumN7HWodk2+WIYAwWmIW+b9JPd4Tj7M+88f/HFmwGLlHYs4
   kWe+U0dxrRop9IwsuzdIkrTByn1BFtHO7bhj9zCA9LEeeAionVFqSAnYEmlrOF+ajb1jZ+j
   Fr/6YS1MoPpKeW/k1Fti/rKbos1mC4S0UpyYYng949let9RH0t/aYmtP16J6DtD4mJn67Rp
   TMu6IBtQvJTxGlKYEPHzDSeHKLGr4EpmL2tWTV0AL0itlvXgJypJUb3QQQvJFpkAyLh8+ei
   6MhvtR0SsbffhBPnx58TVML0UMIMR4TUZvO7rKJxIgdFJqru26DTN8iE&affiliate_id=3
   487&strip_google_tagmanager=true

PUHUNAN

   pu·hú·nan

   puhúnan
   investment

   puhunan
   business capital

   pamumuhunan
   investment

   mamuhunan
   to invest

   sa puhunan
   at cost

   sa puhunang limandaang piso
   with an investment of five hundred pesos

   sa puhunang tatlong daang piso
   with a capital of three hundred pesos

MGA KAHULUGAN SA TAGALOG

   puhunan: kapital

   puhunan: halaga ng kalakal na binili

   puhunan: halagang taglay bago magsugal o magnegosyo

MGA KAHULUGAN SA TAGALOG

   puhúnan: yaman na ginagamit o maaaring gamitin sa paglikha ng higit
   pang yaman

   puhúnan: anumang pinagmulan ng tubò o kapangyarihan

   ipámpuhúnan, ipuhúnan, magpuhúnan, puhunánan, puhunánin

   pamuhunanan pamumuhunan pinamuhunan pinamuhunanan pinamumuhunanan
   pinuhunan pinupuhunan puhunanin pupuhunanin pinapupuhunan
