

PULOT

   This word has at least two different meanings.
     __________________________________________________________________

   dampot, pagkuha ng isang bagay na nasa ibaba

   pulot
   picking up from the ground

   mamulot
   to pick up things, glean

   makápúlot
   to happen to pick up, find
     __________________________________________________________________

   malapot na matamis; tunaw na matamis na panghalo sa inumin ng kabayo;
   arnibal, sirup; puyaw, bagkat

   pulot
   honey, syrup
     __________________________________________________________________

   pulot-gata
   honeymoon

   magpulot-gata
   to have or go on a honeymoon
