

PULONG

   Kahulugan sa Tagalog: pagtitipon ng mga kasapi ng isang kapisanan

   pulong
   meeting

   kapulungan
   assembly

   magpulong
   a lot of people to meet

   pinulong
   gathered people to meet
   = assembled

   pulong-balitaan
   press-con

   magkasámang pulong balitaan
   joint press conference

   Mga may kaugnayang salita: miting, komperensiya, asamblea

   Dito nagpupulong ang mga lokal na pamilya para sa mahahalagang okasyon.
