

PUNA

   puná: remark, observation

   puná: criticism

   punahín: to remark; observe, notice

   pamumuna: the act of criticizing
     __________________________________________________________________

   napuna: noticed

   Napuna ko ang pamamayat ni Ana.
   I noticed Ana’s weight loss.
     __________________________________________________________________

   puna: ino, pansin, pintas; masid
