

PUSLIT

   puslít: smuggling, low-key escape

   puslít: squirt, spurt

   pumuslit: smuggled out of a place

   May pumuslit na lumang kanta sa kanyang bibig.
   An old song slipped out of her mouth.
     __________________________________________________________________

KAHULUGAN SA TAGALOG

   puslit: pulandit

   puslit: biglang paglitaw

   puslit: bagay na kinuha sa masamang paraan, ismagel
