

PUWA

   pú·wa

   from the Spanish pua

   púwa
   plectrum

   A plectrum is a thin flat piece of plastic, tortoiseshell, or other
   slightly flexible material held by or worn on the fingers and used to
   pluck the strings of a musical instrument such as a guitar.

MGA KAHULUGAN SA TAGALOG

   púwa: lagsák o paglagsak (pagtatambak ng maruruming bagay)

   púwa: sa larangan ng musika, pangkalabit ng gitara
