

PUWESTO

   This word is from the Spanish puesto (meaning: spot).

   puwesto
   place

   puwesto
   position

   puwesto
   employment
     __________________________________________________________________

   nakapuwesto
   in position

   ipuwesto
   to install in place

   ipinuwesto
   installed in place

   naipuwesto
   was able to put in place

   pumuwesto
   to take a position

   spelling variations: pwesto, pumwesto, naipwesto, ipwesto, nakapwesto
