

SABI

   pronounced SAH-bee

   deklarasyon, pahayag, diga, wika

   sabi
   statement, to say

   Sabi ko…
   I say… / I said…
     __________________________________________________________________

   sabihin
   to say, to tell

   Sabihin mo sa kanila.
   Tell them.

   Sabihin mo sa akin.
   Tell me.

   Sabihin mo sa presidente kung ano ang ginawa mo.
   Tell the president what you did.
     __________________________________________________________________

   pasabi
   message sent
     __________________________________________________________________

   pakisabi
   please tell

   Pakisabi mo kay Ana na kailangan siya dito.
   Tell Ana she’s needed here.
     __________________________________________________________________

   magsabi
   to say, tell, state

   Magsabi ka ng totoo.
   Tell the truth.
     __________________________________________________________________

   nasabi
   have already said, told

   Nasabi mo na ba sa nanay mo?
   Have you already been able to tell your mother?
     __________________________________________________________________

   pagsabihan
   to reprimand

   Pagsabihan mo ang anak mo.
   Discuss things with your child.
     __________________________________________________________________

   sa madaling sabi
   in short

   Sa madaling sabi, tinamad ka kaya hindi ka pumunta.
   In short, you were lazy so you didn’t go.
