SABOG

   isabog: ikalat, ipamudmod, ipamahagi; ihasik, isaboy; itapon sa iba’t
   ibang dako

   sabog
   scattering

   sabog
   explosion, blast

   pagsabog
   explosion

   pagpapasabog
   bombing

   pagsasabog: pagkakalat, paghihiwa-hiwalay, kalat-kalat, layu-layo,
   iba-ibang lugar, nagsasabog
     __________________________________________________________________

   sabóg
   wasted from drugs
   (slang word)

   Sabóg ka ba?
   Are you high?
   (on drugs)
