

   ____________________

Meaning of "sabungan"

sabungan •

   n.
     *
          + cockpit

» synonyms and related words:

   cockpit
   n.
     *
          + sabungan

   malas
   Sp n.
     *
          + bad luck [syn. walang suwerte, buwisit] malasin (-in)

   v.
     *
          + to suffer bad luck. Minalas siya sa sabungan kahapon. He had
            bad luck at the cockpit yesterday.


