

SAGANA

   Please see the entry for the adjective masagána.

   sa·ga·nà

MGA KAHULUGAN SA TAGALOG

   saganà: labis-labis ang dami

   pasasa, labis, nagkakatusak, marami, tambak-tambak, labis sa kailangan,
   limpak-limpak

   Sinasabi na noong unang panahon, ang uring ito ng ibon ay
   saganang-saganang matatagpuan sa isang kapatagan, ang kapatagang nasa
   kasalukuyang pook ng bayan.

   pagsasagana ng kabuhayan
