SAGWAN

   This word is from the Spanish zagual.

   sag·wán
   paddle

   nagsasagwan
     __________________________________________________________________

   Ano ang kaibahan ng “oar” sa “paddle”?
   What’s the difference between an oar and a paddle?

   Ang “oar” ay nakakabit sa bangka.
   An oar is connected to the boat.
     __________________________________________________________________

MGA KAHULUGAN SA TAGALOG

   sagwán: panggaod

   sagwán: kasangkapan sa pagpapatakbo ng bangka
