

SAKIM

   sakím: avaricious, covetous, greedy, selfish

   masakim : avaricious, greedy, rapacious, selfish

   kasakiman: greed; greedy behavior

   Pagbabayaran ng kinabukasan ang kasakiman ng nakaraan.
   The future will pay for the selfishness of the past.

MGA KAHULUGAN SA TAGALOG

   sakím: may matindi at makasariling lunggati para sa yaman,
   kapangyarihan, o pagkain

   masakim: maimbot, makamkam, mayamo, maramot, suwapang, ganid
