

SAKLOB

   sak·lób

   saklób
   concave lid

   This often refers to the cover or lid covering a clay plot.

MGA KAHULUGAN SA TAGALOG

   saklob: pankalob, suklob, takob, takip

   saklób: malukong na pantakip sa palayok

   saklób: pagkakapatong na magkaharap, gaya ng dalawang pinagtaklob na
   larawan

   saklób: pagpapatong ng sombrero sa ulo

   saklób: pagsososyo sa pamumuhunan gaya ng sa negosyo o sugal

   pinagsaklob, pinagsakluban

   Ang lahat ng payok, may katapat na saklob.
