

SAKOTE

   This Tagalog word is slang.
   sakote
   catch, arrest

   Sakote ang tatlo.
   The three were caught.

   masakote
   to be caught, apprehended, arrested

   para masakote ang suspek
   in order to apprehend the suspect

   Hindi masakote.
   Can’t be apprehended.

   nasakote
   was caught
     __________________________________________________________________

   The more standard word for ‘catch’ is huli.
