

SALAWAL

   pantalon, kalsonsilyo; brip, panti

   salawal
   underwear

   This word is considered old and outdated. Most Filipinos now use the
   English terms “brief” and “panty” to refer to male and female
   underwear, respectively.

   In American English, it’s “panties” and “briefs” — in the Filipino
   language, it’s panti and brip.

KAHULUGAN SA TAGALOG

   salawal: pang-ibabâng damit, gaya ng pantalon, karsonsilyo, at shorts
