

SALAKAY

   salakayin: pasukin, digmain, lusubin

   salakay
   attack, assault

   bantáy-salakay
   dishonest guard

   (The person entrusted to be the guard ends up being the culprit.)
     __________________________________________________________________

   salakayin
   to attack

   Sasalakayin nila ang kapitolyo.
   They will attack the capital.
     __________________________________________________________________

   sinalakay
   attacked

   sinalakay ng ibang bansa
   attacked by another country
     __________________________________________________________________

   Related Tagalog words:

   daluhong, paglaban, salakay, paglusob
