

SALBAHE

   This word is from the Spanish salvaje.
   sal·bá·he
   naughty

   Salbaheng aso.
   Naughty dog.

   Salbahe ang anak mo.
   Your child is naughty.

   Salbahe ka talaga.
   You’re really naughty.

   Inaadmit ko na salbahe ako.
   I admit that I am naughty.

   non-standard spelling variation: salbaje

MGA KAHULUGAN SA TAGALOG

   salbáhe: mabangís

   salbáhe: hindi mapagkakatiwalaan, hindi sumusunod sa utos at mahilig
   gumawâ ng kalokohan
