

SALIGAN

   root word: sálig

MGA KAHULUGAN SA TAGALOG

   salígan: batayán

   salígang-batás: konstitusyón

   sálig: batay o magbatay

   isálig, magsálig, pagsalígan

   [66]PREAMBLE, [67]ARTICLE I National Territory, [68]ARTICLE II
   Declaration of Principles and State Policies, [69]ARTICLE III Bill of
   Rights, ARTICLE IV Citizenship, ARTICLE V Suffrage, ARTICLE
   VI Legislative Department, ARTICLE VII Executive Department,
   ARTICLE VIII Judicial Department
