

SAMO

   sa·mò

   samò
   pleading

   samò
   supplication

MGA KAHULUGAN SA TAGALOG

   samò: hiling

   pagsamò, pagsusumamò: madamdaming paghiling na gawin o ibigay ang isang
   bagay

   Mauuna sa tindiga’y ang panig na maghahayag,
   Bago muna mag-asawa’y magpagulang ang marapat;
   Kaya naman ang samo ko, kay Elenang isang dilag,
   Sa kislap ng katwira’y palitawin ang liwanag;
   Narito na si Elenang sa pingkia’y magbubukas.
