

SANGKAP

   lahok, halo, ingridyent, kondiment, rikado, bahagi

   sangkáp
   part, element

   sangkáp
   ingredient

   mga sangkáp
   ingredients

   mga sangkáp para sa tinapay na yari sa tahanan
   ingredients for bread made at home
     __________________________________________________________________

   kasangkapan
   tool, instrument

   isangkap
   to use as an ingredient

   panangkap
   raw material
