

SAPAK

   pagkabali ng sangay ng kahoy; ingay na likha ng bibig sa pangunguya;
   sagad sa puluhan; baung-baon, tagos, upos
   sapak
   punch, hit

   Gusto kitang sapakin.
   I want to hit you (with my hand).

   sinapak
   smacked

   pananapak
   beating

   Nauwi sa pananapak.
   Ended up in a beating.
     __________________________________________________________________

   Related Tagalog word:
   [66]tama
   hit inadvertently

   Natamaan ako ng bato.
   I was hit by a rock.
