

SAPI

   This word has at least two meanings in standard dictionaries.
     __________________________________________________________________

   sapì
   ply

   sapì
   reinforcement

   sapian
   to reinforce
     __________________________________________________________________

   sapì
   business stocks

   pagsapì
   membership

   kasapì
   member

   magsapì
   to join together

   sumapì
   to join
     __________________________________________________________________

MGA KAHULUGAN SA WIKANG TAGALOG

   sapi: sosyo, sama, istak

   sapi: patibay, patigas

   sapi: pakikiisa, pakikipangkat
     __________________________________________________________________

   sapi / sapian: samahan, singitan ang puwang upang humakab o lumapat
