

SAPOL

   sa·pól

   sapulín ang ibig sabihin

   Hindi ko masapol ang ugnayan ng dalawa.

   Bungkalin mo ang kalansay sa apog at lumot ng gunita upang masapol ang
   katotohanan.

MGA KAHULUGAN SA TAGALOG

   sapól: sa simula pa lámang

   sapól: patamaan o tamaan nang matindi o buong buo

   sapól: putulin hanggang sa ugat

   * sapól: makita kung sino ang hinahanap

   sapól: makarating sa tamang pagkakataon

   sapól: gawin lahat nang magkasabay

   sapól: sabihin nang walang inililihim
