

SARÁ

   This word is from the Spanish cerrar (meaning: ‘to close’).

   sará
   closed

   Isara mo ang pinto.
   Close the door.

   Isara ang lahat ng bukas na bintana.
   Close all the open windows.

   Isara mo ang iyong mata.
   Close your eyes.

   Isinara ang daan.
   The road was closed.

   Bakit isinara ang bangko?
   Why was the bank closed?

   Bakit nagsara ang bangko?
   Why did the bank close?

   [66]sarado
   closed
