

   ____________________

Meaning of "sarap"

sarap •

   adj.
     *
          + masarap (ma-) delicious, good

» synonyms and related words:

   relish
   n.
     *
          + 1. a good flavor, pleasant taste: linamnam, sarap, kasarapan
          + 2. liking, appetite: gana, pagkakagana, gusto, pagkakagusto
          + 3. something to add flavor to food: pampalasa, pampasarap

   v.
     *
          + to like the taste of: magkagusto, magustuhan, maibigan


