

SARI

   sari
   kind, class

   aral-sari
   sexology
   (see sariin)
     __________________________________________________________________

   sari-sari
   all kinds

   sari-sari
   various

   sari-saring bagay
   various things

   sari-saring paninda
   various items being sold
     __________________________________________________________________

   sari-sari
   store that sells various small items

   tindahan
   store

   sari-saring tindahan
