

SAYA

   sayá: tuwa, galak, ligaya, lugod, pagtatamasa
   sayá
   joy, happiness, fun

   Ang saya!
   So much fun!

   masaya
   happy

   ipagsaya
   to celebrate

   sumaya
   to cheer up

   Ang saya ‘pag kasama ang pamilya.
   Loads of fun when with the family.
     __________________________________________________________________

   saya: palda, pang-babang damit
   saya
   traditional Filipina skirt

   sayang puti
   traditional skirt that’s white in color
