

SAYSAY

   statement; value

MGA KAHULUGAN SA TAGALOG

   saysáy: pahayág

   saysáy: halagá

   nagsaysay: nagpahayag; nagsabi

   ipinagsaysay: ipinahayag, sinabi

   Ang lahat ng ipinagsaysay ay dapat gunitain at mahinahong
   pagbulaybulayin sapagkat di magaganap at di matitiis ng walang tunay na
   pagibig sa tinubuang lupa, at tunay na adhikang ipagtangkilik ang
   Kagalingan.

   Si Donya Maria’y nagsaysay, “Ulitin ninyo ang sayaw.”
