

SIBAK

   sibakin: biyakin, tilarin ang kahoy sa pamamagitan ng paggamit ng
   palakol o gulok

   sibák
   chopping wood

   sibák
   coitus (slang)
     __________________________________________________________________

   sinibak
   fired, dismissed, axed (slang)

   Sinibak ang tatlong opisyal.
   The three officials were fired.

   Sisibakin ka daw sa pwesto.
   You’ll reportedly be let go from your position.

   Related Tagalog slang words: [66]sisante, [67]talsik
