

SIKAP

   masikap, masinop, masikhay, masigasig

   sikap
   diligence, hard work

   masikap
   diligent, industrious

   magsikap
   to endeavor, make an effort to

   magsumikap, pagsumikapan
   to strive

   nagsusumikap
   is striving

   pagsikapan
   to try, attempt

   pagsisikap
   attempt, effort, enthusiasm, zeal

   sikapin
   to try, seek

   sariling sikap
   slang for masturbation

   oras at pagsisikap
   time and effort
