

SILBI

   This word is from the Spanish serví.

   silbi
   service, utility

   tagasilbi
   server

   walang silbi
   useless, without utility

   Wala kang silbi.
   You’re useless.

   nagsilbing inspirasyon
   served as inspiration

   Anong silbi nito?
   Of what use is this?

   Manilbi, manilbihan…
   To serve…

   sinisilbihan
   is serving (someone)

   Pinagsisilbihan ko ang Diyos.
   I am serving God.
