

   ____________________

Meaning of "silbi"

silbi •

   v.
     *
          + magsilbi, isilbi (mag-:i-) to serve. Nagsisilbi na ang weyter.
            The waiter is serving already.

» synonyms and related words:

   useless
   adj.
     *
          + 1. of no use, worthless: walang kasaysayan, walang kaukulan,
            walang kuwenta, walang silbi, inutil, walang kagamitan
          + 2. not needed, not necessary: hindi kailangan


