

SINTA

   Sinta is an old-fashioned Tagalog word for ‘love.’

   Sinta ko. = Aking sinta.
   My dearest.

   [66]Pasko na, sinta ko. (song title)
   It’s Christmas already, my love.

   kasintahan
   sweetheart

   magkasintahan
   sweethearts, lovebirds

   Sinisinta kita.
   I love you.

   These days, most Filipinos use the word [67]mahal in most contexts, and
   the word [68]ibig in more dramatic situations.
