

SOBRA

   Sobra kitang minahal.
   I loved you too much.

   lábis; may surplas
   sóbra
   too much

   sobra
   excessive

   sobra-sobra
   way too much

   sobrang [66]timbang
   overweight = obesity

   Sobrang init.
   Too hot.

   Sobrang init sa Pilipinas.
   It’s too hot in the Philippines.

   May natirang sobrang pagkain.
   There’s excess food that was left over.

   Mahal kita, sobra!
   I love you, overly!

   Sumosobra ka na.
   You’re being too much now.
