

SUBALI

   subali: objection or reservation

   nagpapasubali: to be making reservations or objections

   Walang nagpapasubali sa relihiyon noon.
   No one had reservations about religion before.
   In the old days, no one had objections to religion.
     __________________________________________________________________

MGA KAHULUGAN SA TAGALOG

   subali: nguni, datapwa

   [66]subali’t: nguni’t, datapwa’t

   nagpasubali, magpapasubali, subalian, mapasubalian
