

SUBOK

   alamin kung kayang gawin
   subok
   trial, test, experiment

   subukin
   to try, to put someone or something to the test

   subukan
   to try something out, to taste something

   Subukan mo ito.
   Try this.

   Subukan mong kumain.
   Try to eat.

   Subukan mo lang.
   Just try it.

   Subukan mong gawin ang sinabi ko sa iyo.
   Try to do what I told you.

   nanunubok
   is testing
