

SUBUKAN

   root word: subok (attempt)

   subukan
   to try something, attempt

   Subukan mo ito.
   Try this. (Taste this.)

   Tikman mo ito.
   Taste this.

   Subukan mong kumanta.
   Try singing.

   Subukan mong bumangon.
   Try to get up.

   Susubukan ko.
   I’ll try.

   Sinusubukan ko.
   I am trying (it out).

   Susubukan kong matulog.
   I’ll try to sleep.

   Susubukan ko itong kainin.
   I’ll try to eat this.
