

   ____________________

Meaning of "suwail"

suwail •

   adj.
     *
          + rebellious, disobedient, insolent

» synonyms and related words:

   rebellious
   adj.
     *
          + 1. defying authority, acting like a rebel: mapanghimagsik,
            mapaghimagsik, mapanlaban
          + 2. insolent: suwail, balawis

   tampalasan
   adj.
     *
          + wicked, perverse, destructive [syn. buhong, imbi,
            walang-pakundangan, suwail]


