

TAAS

   tayog, tangkad, layog; timbaw; kamahalan; kabunyian; kadakilaan
   taás
   height

   [66]mataás
   tall, high

   itaás
   to hoist, raise, lift

   nakatataas
   senior in rank

   naitataas
   able to be lifted

   pagmamataas
   pride

   pataasan
   competition

   pataasin
   to raise

   sa itaas
   overhead, above
     __________________________________________________________________

   tumaas
   to rise, increase, ascend

   tumataas na presyo
   rising price(s)
