

TAGAL

   laon, tibay, luwat, resistensiya; tatag, tiis, agwanta; pagbabata
   tagál
   duration

   matagal
   takes a long time

   Ang tagál mo.
   You’re taking so long.
     __________________________________________________________________

   katagalan
   long duration

   makatagal
   to be able to last

   magtagal
   to last

   magpatagal
   to prolong

   pangmatagalan
   lasting a long time

   patagalan
   test in endurance
