

TAGPÔ

   pagkakakita, pagkakasumpong; eksena

   tagpô
   scene, circumstances

   pagtatagpô
   meeting, appointment

   makatagpô
   to discover, come across

   magtagpô
   to meet, converge

   matagpuán
   to happen to find, discover

   natagpuan sa tabing kalsada
   found by the side of the road

   tagpuan
   meeting place, rendezvous

   tagpuín
   to go and meet

   pinagtagpo
   made to meet
