

TAKOT

   pangamba, sindak

   takot
   fear

   May takot ako sa Diyos.
   I am God-fearing.
     __________________________________________________________________

   takót
   scared, fearful

   Takót ako sa tubig.
   I’m afraid of water.

   Takót akong mag-isa.
   I’m afraid to be alone.
     __________________________________________________________________

   matakot
   to be afraid

   Huwag kang matakot.
   Don’t be afraid.

   Hindi ako natatakot.
   I’m not afraid.
     __________________________________________________________________

   manakot
   to scare

   Huwag kang manakot.
   Don’t scare (people).
   Don’t spread fear.
     __________________________________________________________________

   takutin
   to frighten

   Huwag mong takutin ang bata.
   Don’t scare the child.

   Tinakot ba kita?
   Did I scare you?
     __________________________________________________________________

   nakakatakot
   frightening

   Nakakatakot ang nakita ko.
   What I saw was scary.

   pananakot
   scaring, intimidation
