

TALAHIB

   This is a tall grass whose scientific name is Saccharum spontaneum.

   taláhib
   tall grass

   In common usage, tall grasses with long coarse-surfaced leaves are
   referred to as talahib even if they’re not necessarily of the same
   classification family.

KAHULUGAN SA TAGALOG

   talahib: damong mataas, magaspang ang dahong patulís at tuwid, masanga
   at mabalahibo ang tangkay, at may putî at malasutlang maliliit na
   bulaklak
