

TAMBALAN

   root word: tambal

   tambalan
   a pairing

   tambalang-salita
   paired words, compound words

   tambalang pangungusap
   compound sentence

   Ang kasalungat na salita ng tambalan ay payak.
   The antonym of the word compound is the word simple.

   Mga Halimbawa ng Tambalang Salita sa Tagalog:
   Examples of Compound Words in Tagalog:

   agaw-buhay, bahay-aliwan, silid-tulugan, madaling-araw, biglang-yaman
