

TAMIS

   lasa ng asukal
   tamis
   sweetness

   matamis
   sweet

   minatamis
   something candied,
   sweetened

   patamisin
   to sweeten

   magpatamis
   to sweeten

   tumamis
   to become sweet

   matamisin
   to make sweet

   katamisan
   sweetness

   matamis and dila
   “sweet-tongued”
   = glib, skilled at saying sweet things

   Sabi umano ni Lacson, hindi raw siya pahuhuli nang buhay at mas
   matatamisin pang mamatay nang may dignidad kaysa sumuko.
