

TANGAY

   tangay: dala, dagit, sapilitang pagkuha, agaw, saklot, daklot, sunggab;
   anod

   natangay: was carried away by the wind

   tumangay: to carry off, snatch away

   May pusang tumangay sa pritong isda.
   There was a cat that snatched and carried away the fried fish.

   parang may tangay na buto
   = as if carrying a bone
   = does not stop murmurring (uncommon idiomatic expression)

KAHULUGAN SA TAGALOG

   matatangay: madadala
