

TANGI

   naiiba sa kasama o sa lahat; liban; di-pangkaraniwan; bukod,
   bukudtangi; nag-iisa, bugtong

   tangi
   only, particular

   tangi
   exceptional, special

   Ang Tanging Ina
   The Only Mother

   ang aking tanging tagumpay
   my only victory
     __________________________________________________________________

   Sometimes the slang word tange is spelled tangi.
   Tange!
   Idiot.
