

TANGKAD

   tang·kád

   tangkád: tallness and slenderness

   matangkád: tall

   tatangkad: will grow tall

   This often refers to a person’s height. For things that are tall or
   high, the word more often used is taas (mataas).

   Non-standard spelling variations: tankad, matangkad, tatankad

MGA KAHULUGAN SA TAGALOG

   tangkád: pagiging mahabà ang binti

   tangkád: pagiging balingkinitan at mataas ang pangangatawan
