

TANTO

   Also see [66]matanto.

   tantô: realize, understand

   napagtanto: realized, understood, grasped

MGA KAHULUGAN SA TAGALOG

   tanto: taho, batid, alam, tatap, tarok, talastas, unawa, intindi

   Mahirap tantuin ang kahihinatnan ng mga manggagawa pagkatapos ng
   nangyari.
     __________________________________________________________________

   Bakit napagtanto at hindi natanto?

   Sagutin sa ibaba.
