

TARANTA

   di-malaman ang gagawin, magulo ang isip; matulig, matuliro, malito
   taranta
   confusion, bewilderment

   katarantahan
   state of confusion, bewilderment

   mataranta
   to be confused

   taratahin
   to confuse, baffle, bewilder

   Nataranta ako.
   I panicked.

   Maghanda ka nang maaga para hindi ka mataranta pagdating ng panahon.
   Prepare early so that you won’t panic when the time comes.
