

TARANTADO

   This word is from the Spanish atarantado.

   ta·ran·tá·do
   foolish + shameless

   tarantado
   silly + disrespectful

   Closer to the nuance, see below:

   Tarantado ka.
   You’re a stupid asshole.
   You’re a moron.

   Isa ka pang tarantado.
   You’re another asshole.

MGA KAHULUGAN SA TAGALOG

   tarantádo: walang prinsipyo o pag-aatubiling moral

   tarantádo: may masamâng gawain o pag-aasal
