

TATAY

   itay, ama, atang, tata
   tatay
   dad, daddy


   ang tatay ko
   my Dad

   ang aking tatay
   my Dad

   Sinong tatay mo?
   Who’s your daddy?

   Ako ba ang tatay mo?
   Am I your Daddy?


   This word is shortened to Tay when addressing your Dad.
   Tay, aalis na po ako.
   Dad, I’m leaving now.


   Remember to use the respectful word po with your tatay!

   Another Tagalog word for ‘Dad’ is Itay.

   The formal word for ‘father’ in Tagalog is ama.
