

TATAG

   tatag: establishment, stability

   itatag: to establish, set up, organize, form

   patatagín
   to firmly establish

   tagapagtatág
   founder

   tatagán
   to make firm

   walang-tatag
   not reliable, shaky

KAHULUGAN SA TAGALOG

   magtatag: magpundar, magtayo, mag-umpisa, mag-organisa

   nagtatag: nagpundar, nagtayo, nag-umpisa, nag-organisa

   tumatatag, nakapagpatatag, pinatatatag, matatag, mapgpakatatag,
   nagpakatatag, papapatatag, ipapatatag, ipatatag
