

TAWID

   paglipat sa kabila

   tawíd
   crossing

   magtawíd
   to carry across

   tumawíd
   to cross

   Tumawíd ka dito.
   Cross here.

   Huwag kang tumawíd dito.
   Don’t cross here.

   táwiran
   crossing point, crosswalk

MGA KAHULUGAN SA TAGALOG

   itawíd, tawirín, tumawíd

   tawíd: dumaan mula sa isang panig túngo sa kabilâ

   tawíd: banderola na isinasabit sa pisi at itinatalì sa magkabilâng
   gilid ng lansangan, karaniwan kung pista
