

   ____________________

Meaning of "tenga"

tenga •

   n.
     *
          + ear, originally pronounced tainga or taynga

» synonyms and related words:

   pitik
   v.
     *
          + pumitik (-um-) to snap one's fingers, to topple or push with a
            flip of the fingers mamitik, pitikin (mang-:-in)

   v.
     *
          + to flick. Pinitik ni Lito ang tenga ni Boyet. Lito flicked
            Boyet's ear.


