

TIGOK

   This is a slang word. It has recently come to mean “dead.”

   The standard word for “dead” is patay.
     __________________________________________________________________

   tigok: lagok, lunok, lulon, tagok

   tigok: to feel uncomfortable eating a particularly desirable food
   without a child or other loved one joining in

   In the Visayas region, tigok is a name for a plant whose scientific
   name is Fimbristylis globulosa.
