

TINDA

   This word is from the Spanish tienda (meaning: store).

   tinda, v
   to sell

   tinda, n
   merchandise

   ang ipinagbibili
   the stuff being sold

   magtinda
   to sell

   [66]tindero
   a male seller

   tindera
   a female seller

   paninda
   stuff being sold in a store or by someone

   paninda
   merchandise

   tinda-tindahan
   children’s game where they pretend to run a store

   The Filipino word for ‘store’ is [67]tindahan.
