

   ____________________

Meaning of "tindi"

tindi •

   n.
     *
          + ponderousness, intensity, gravity, heaviness

   adj.
     *
          + matindi (ma-) grave, intense ponderous, heavy

» synonyms and related words:

   intensity
   n.
     *
          + 1. extreme degree, greatness: tindi, katindihan, sidhi,
            kasidhian
          + 2. great vigor, strength: lakas, kalakasan


