

TIPON

   tí·pon: collection

   katipunan: assembly, federation

   magtipon: to collect, gather

   nagtipon: collected, gathered

   future tense: titipunin

   pagtipun-tipunin: to bring together, assemble

   tipunan: place of assembly

MGA KAHULUGAN SA TAGALOG

   pagtitípon: pagsasáma-sáma ng mga tao o mga bagay

   katipúnan: pagpilì ng mga bagay upang pagsamá-samáhin alinsunod sa uri,
   antas, at katulad na pamantayan, gaya sa katipúnan ng mga akdang
   pampanitikan
