

TIRA

   This word has at least three meanings.
     __________________________________________________________________

   tira, pagtira
   residence

   manirahan
   to reside

   nakatira
   resident, living in

   Sino ang nakatira dito?
   Who lives here?
     __________________________________________________________________

   tira
   leftover, residue

   tira-tira
   leftovers

   itira
   set aside

   tirhan
   to spare, leave for someone
     __________________________________________________________________

   tira, matira
   be able to endure

   Matira ang matibay.
   May the strong survive.
