

TIYAN

   dakong labas o ibaba ng sikmura; puson, buyon

   tiyán
   abdomen, stomach

   tiyán
   belly

   sa tiyán mo
   in your tummy

   sakit ng tiyán
   stomachache

   Masakit ang tiyan ko.
   My tummy hurts.

   Kumukulo ang tiyan ko.
   My tummy is “boiling.”
   = My stomach is growling / rumbling.
   pulikat sa tiyan
   stomach cramps

   pananakit sa tiyan
   stomach pains

   The Filipino word pusón refers more to the lower abdomen.
