

TIYAK

   sigurado, nakasisiguro; tinuturol nang lubusan, walang pasubali o
   alinlangan

   tiyak
   definite

   tiyak na tunguhin
   definite goal

   tiyak na paksa
   definite topic

   Ang kasalungat ng salitang panlahat ay tiyak.
   The antonym of the word general is specific.

   Cross-reference: paniniyak

   di-nakatitiyak makakatiyak mapaniyak nakatiyak naniniyak pagkakatiyak
   pakatiyakin titiyakin titiyak tumitiyak walang-katiyakan
