

TODAS

   This word is likely from the Spanish todas (meaning: all).

   It’s sort of a slangy word for “to kill.”

   Totodasin ko sila.
   I’ll finish them off.
   = I’ll kill them all.

   todasin: lahatin,ubusin, lalusin; patayin

   Non-standard spelling variations: tudas, tutudasin
     __________________________________________________________________

   The general word for “to kill” is patayin.

   Papatayin ko sila.
   I’ll kill them.
