

TOROTOT

   torotot (pink)

   to·ró·tot

   torotot
   child’s trumpet

   mga torotot
   party horns

   Torotot is like a noisemaker for parties, but in the Philippines, its
   use is more prevalent in the run-up to the New Year.

   uncommon spelling variation: turútot

MGA KAHULUGAN SA TAGALOG

   torótot: trumpéta

   torótot: laruang hinihipang tíla trumpeta var

   torótot (kolokyal): ang pagtataksil ng babae sa kaniyang asawa

   torótot (kolokyal): pindého
