TOTOÓ

   pronounced TOH-TOH-OH

   tunay, hindi kasinungalingan, tapat
   totoó
   true, real, genuine

   Totoó ang sinasabi ko.
   What I’m saying is true.

   Totoong totoo.
   Very real.

   Totoong malaki ang bahay nila.
   It’s true their house is big.

   katotohanan
   truth

   makatotohanan
   realistic

   nagkatotoo
   became real

   Misspellings: tutuo, nagkatutuo
     __________________________________________________________________

   A similar Tagalog word is talaga.
