

TSUPER

   This word is from the Spanish chófer.

   tsupér
   driver

   tsupér
   chauffeur

   nagtrabaho bilang tsuper
   worked as a chauffeur

   mga tsuper ng taksi
   taxi drivers

   Nagprotesta ang mga tsuper sa pagtaas ng presyo.
   The drivers protested the price increase.

   Pinagkaisang Samahan ng mga Tsuper at Opereytor Nationwide (PISTON)
   United Organization of Drivers and Operators Nationwide
