

TUBO

   This word has many meanings.

   tubo (Spanish origin)
   pipe, tube, conduit
     __________________________________________________________________

   tubo
   gain, profit, interest

   patubuan
   lending money with interest
     __________________________________________________________________

   tubó
   sugarcane

   Tubo (Philippine Sugarcane) Tubo (Philippine Sugarcane)
     __________________________________________________________________

   tubò
   native

   See katutubo.
     __________________________________________________________________

   tubo
   sprout, growth

   tumubo
   to grow

   magpatubo
   to grow a plant

   magpatubo ng balbas
   to grow a beard
