

TUKLAW

   kagat ng ahas, sagpang; tuka

   tuklaw
   snakebite

   Tinuklaw ako ng ahas.
   A snake bit me.

   kontra-tuklaw
   “against snakebite”
   = antivenom
   = snakebite prevention

   manunuklaw
   something that bites

   Namatay ang bata sa tuklaw ng ahas.
   The child was killed by a snakebite.

   natuklaw
   was bitten
   (by a snake)

   Namatay ang isang 10-anyos na batang lalaki makaraang matuklaw ng
   kobra.
   A 10-year-old boy died after being bitten by a cobra.
