

TUKSO

   tuk·só
   tuksó
   temptation, seduction

   Tuksó, layuan mo ako.
   Temptation, stay away from me.
     __________________________________________________________________

   manukso
   to tempt

   panunukso
   the act of tempting (someone)
     __________________________________________________________________

   tukso
   teasing, joking

   Tinukso niya ako.
   He/She teased me.

   Tinukso niya akong mataba.
   He/She teased that I was fat.

   magtuksuhan
   to tease one another

   manukso
   to tease

   mapanukso
   in the habit of teasing

   Mapanukso ang panahon.
   The weather is a tease.

   mapanuksong sayaw
   teasing dance, seduction dance

   panunukso
   teasing

   Labis ang panunuksong ginawa mo. Umiyak tuloy ang bata.
   The teasing you did was excessive. The child ended up crying.
