

   IFRAME:
   https://www.fiverr.com/embed_gigs?id=U2FsdGVkX1+CFUvPA6U6f9Q8B066qG
   3SoJUc4gasZRoKeniO9FhK/9jXOeYNRzwGINh7+BcRfPMXTYsa6SZt5uMl6Cd78wxViy6B+
   fWQUXlKigdvwlEibD5PvkDswNFQft2m0bvcmyOq3C/nYwjdOTfz8dxhGoBQyuKPIYJI56QU
   NGp5VLoP+FpcDrAAxbjKQlgHumN7HWodk2+WIYAwWmIW+b9JPd4Tj7M+88f/HFmwGLlHYs4
   kWe+U0dxrRop9IwsuzdIkrTByn1BFtHO7bhj9zCA9LEeeAionVFqSAnYEmlrOF+ajb1jZ+j
   Fr/6YS1MoPpKeW/k1Fti/rKbos1mC4S0UpyYYng949let9RH0t/aYmtP16J6DtD4mJn67Rp
   TMu6IBtQvJTxGlKYEPHzDSeHKLGr4EpmL2tWTV0AL0itlvXgJypJUb3QQQvJFpkAyLh8+ei
   6MhvtR0SsbffhBPnx58TVML0UMIMR4TUZvO7rKJxIgdFJqru26DTN8iE&affiliate_id=3
   487&strip_google_tagmanager=true

TUMINAG

   root word: tínag

   tumínag
   to budge

   tumínag
   budged

   To move without leaving one’s place.

KAHULUGAN SA TAGALOG

   tumínag: gumalaw o kumilos nang hindi umaalis sa kinalalagyan

   Hindi tuminag sa pagkakatayo si Lita.

   Anumang hila ko sa lubid ay hindi tuminag ang aso.

   Alam niyang narinig siya nito. Ngunit hindi ito tuminag sa kinauupan.
