

TUNTON

   tuntón: tracing the path of

   tuntón: tracing the source / origin

   tuntón: giving guidance at the start

   tuntunan: basis
     __________________________________________________________________

   tuntón, pagtutunton: giving guidance at the start

   palatuntunan: regulation (guidance, something that guides)

   tuntunin: rule, principle
     __________________________________________________________________

MGA KAHULUGAN SA TAGALOG

   tunton: sunson, balik, tultol, turo, akay, subaybay

   tunton: pagdaan sa dinaanan ng iba

   tunton: pag-angkin

   tinutunton
