

TUSOK

   tusok: sundot, turok; aspiling pang-belo

   tusok
   piercing, perforation

   nakatusok
   is skewered to

   tusukan
   to pierce, perforate, skewer

   tusukan
   pin cushion

   tinusok ng karayom
   was pierced with a needle

   Huwag mo akong tusukin.
   Don’t prick me.

   natusok
   got pricked

   Natusok ako sa likod.
   I got pricked in the back.

   Natusok ako ng karayom.
   The needle pricked me.

   nanunusok
   is piercing
