

TUSTOS

   tustós / tustusán: to support financially

   panustós: support, allowance, maintenance

   panustós: supply

   matustusan: to be able to spend for or subsidize financially

   maitustos, ipantustos, pagtutustos, itutustos

MGA KAHULUGAN SA TAGALOG

   tustos: pensiyon, sustento, bigay-gugol

   tustos: suplay

   tustos: hugos, luwag, lundo

   tustos: tutos, hilbana, salugsog

   tustos: bulutong, bulutong-tubig

   tagapagtustos

   tinutustos
