

TUTAL

   This is from the Spanish total.

   tutál
   anyway

   Ibigay mo na lang sa akin. Tutal, di mo naman kailangan.
   Just give it to me. Anyway, you don’t need it.

   This word used to be closer to the Spanish meaning — “in total” or “to
   add up” or “to summarize.” Today, it is considered slang. In fact, the
   word as spelled tutal does not appear in standard Filipino
   dictionaries. The standard word and spelling is totál.
