

TUTOL

   kontra, salungat, laban; di-pagsang-ayon sa mungkahi o sa
   pinagkaisahan; reklamo, protesta, oposisyon; habol, apelasyon
   tutol
   objection, disapproval

   tutol
   opposition, protest

   pagtutol
   resistance

   tumutol
   objected

   May tumutol sa kasal.
   Someone objected to the marriage.

   tinutulan
   objected

   tinutulan ang mungkahi
   objected to the suggestion/recommendation

   nagsitutol
