

TUTOK

   tutok
   point (a gun at), aim

   tinutukan ng baril
   to have a pointed a gun at

   Tinutukan ako ng baril.
   I had a gun pointed at me.

   nanutok ng baril
   pointed a gun at

   The general Tagalog word for “point” is [66]turo.
     __________________________________________________________________

   tutok
   aim or focus attention on

   Nakatutok sa kompyuter.
   Focused on the computer.

   Nakatutok ang mga mata sa pangulo.
   All eyes were locked on the president.
