

UHAW

   kalagayan ng kasabikang uminom ng tubig, tumanggap ng kaligayahan,
   pagmamahal, atbp.
   uhaw
   thirst

   uhaw
   thirsty

   uhaw sa pansin
   thirsty for attention

   Uhaw ako.
   I’m thirsty.

   Inuuhaw ako.
   I’m feeling thirsty.

   Inuhaw ako.
   I became thirsty.

   Inuhaw ako sa pagkanta.
   Singing made me thirsty.

   uhaw sa dugo
   thirsty for blood

   uhaw sa pag-ibig
   thirsty for love

   pamatid-uhaw
   thirst-quencher
