

   ____________________

Meaning of "uka"

uka •

   adj.
     *
          + dent, hollowed out

» synonyms and related words:

   worn
   adj.
     *
          + 1. damaged by use: sira, sira-sira, gutay, gutay-gutay
          + 2. worn away (hollowed out or having holes, or worn by
            friction): uka, butas
          + 3. worn off (at the point or ends): pudpod, upod
          + 4. worn thin: gasgas
          + 5. tired, wearied: pagod, hapo, pata


