

ULAT

   ulat
   report, account, statement

   mag-ulat
   to report, give an account of

   Mag-ulat tungkol sa kasaysayan ng Tsina.
   Do a report about the history of China.
     __________________________________________________________________

   iulat
   to report

   Iulat mo kung ano ang nangyari.
   Recount what happened.
     __________________________________________________________________

   Similar-looking Tagalog word:
   magulat
   to be shocked
     __________________________________________________________________

   Related Tagalog word:
   balita
   news
