

UMAMIN

   root word: [66]amin

   umamin
   admitted (confessed)

   umamin na
   admitted already

   Si Pedro, umamin na!
   Peter has confessed already!

   umamin na…
   admitted that

   umamin na aswang
   admitted to being a ghost

   umaming… (short for “umamin na”)
   admitted that…

   Si Ana, umaming buntis.
   Ana admitted that she’s pregnant.

   Umamin si Ana na buntis siya.
   Ana admitted that she’s pregnant.
