

UPANG

   nang sa gayo’y, nang; para
   upang
   in order to

   Sumulat ako upang humingi ng tulong.
   I wrote in order to ask for help.
   = I wrote to ask for help.

   Nabubuhay ako upang umibig.
   I live in order to love.

   Upang gumaling, uminom ka ng gamot.
   In order to get well, take medicine.

   Related Filipino word: para
     __________________________________________________________________

   Unrelated to the above: [66]upa (rent)
