

URONG

   umurong: umudlot, umatras
   urong
   retreat, backward movement

   umurong
   to retreat, withdraw, retract

   Umurong sila nang umurong.
   They kept retreating.

   Umurong and senador sa kampanyang maging presidente.
   The senator withdrew from the campaign to become president.

   pauróng
   backward

   Lumakad akong nang paurong.
   I walked backward.

   urong-sulong
   “going backward, going forward”
   = indecisive, hesitation

   inuurungan
