

UTAS

MGA KAHULUGAN SA TAGALOG

   utas: tapos, lutas, yari, nagwakas, patay na

   nautas: natapos na, namatay

   mautas: matapos na, mamatay

   nauutas: natatapos na, namamatay

   Apat na heneral ay tadtad ng sugat, nabuwal sa kampo’t hininga’y
   nautas.
     __________________________________________________________________

   Naghihingalo ang buwaya at di nga natagala’y hinahanap ang pampang at
   doon na lamang nautas.
