

UWÎ

   pronounced OO-wee

   bumalik (sa tahanan)
   uwî
   return home

   Unang araw ng Agosto ang uwî ko.
   I return home on the first day of August.
     __________________________________________________________________

   uwî
   something brought home

   May uwî akong CD para sa iyo.
   I brought home a CD for you.
     __________________________________________________________________

   pag-uwi
   returning home

   Sasalubungin kita sa airport pag-uwi mo sa Pilipinas.
   I’ll come out to welcome you at the airport when you return home to the
   Philippines.
     __________________________________________________________________

   umuwi
   to go home

   Umuwi ka na.
   Go home already.
     __________________________________________________________________

   mauwi
   to develop into, to happen as a result

   Baka mauwi ito sa kamatayan.
   This might result in death.
     __________________________________________________________________

   pauwi
   on the way home

   Pauwi na ako.
   I’m on my way home already.

   Pauwi na ako nang nakuha ko ang teks mo.
   I was already on the way home when I got your text message.
     __________________________________________________________________

   pauwiin
   to send home

   Pauwiin mo ang bata. Mukha talagang may sakit.
   Send the child home. Looks really sick.
     __________________________________________________________________

   uwian
   usual time to go home, dismissal time

   Anong oras ang uwian ninyo?
   What time do y’all get off? (school or work)
     __________________________________________________________________

   paguwi is a misspelling of pag-uwi.

   non-standard spelling variation: uwe
