

WAGAS

   puro, lantay, walang halo, dalisay, busilak, tunay, tapat

   wagás
   pure

   wagas
   perfect

   Wagás ang ating pagmamahalaan sa isa’t isa.
   Our love for each other is pure and perfect.

MGA KAHULUGAN SA TAGALOG

   wagás: uri ng pinakapurong ginto

   wagás: dalísay

   wagás: matapat at walang halòng pag-iimbot o pagsasamantala

   Paano makikilala ang tunay at wagas na pag-ibig?
