

   IFRAME:
   https://www.fiverr.com/embed_gigs?id=U2FsdGVkX1+CFUvPA6U6f9Q8B066qG
   3SoJUc4gasZRoKeniO9FhK/9jXOeYNRzwGINh7+BcRfPMXTYsa6SZt5uMl6Cd78wxViy6B+
   fWQUXlKigdvwlEibD5PvkDswNFQft2m0bvcmyOq3C/nYwjdOTfz8dxhGoBQyuKPIYJI56QU
   NGp5VLoP+FpcDrAAxbjKQlgHumN7HWodk2+WIYAwWmIW+b9JPd4Tj7M+88f/HFmwGLlHYs4
   kWe+U0dxrRop9IwsuzdIkrTByn1BFtHO7bhj9zCA9LEeeAionVFqSAnYEmlrOF+ajb1jZ+j
   Fr/6YS1MoPpKeW/k1Fti/rKbos1mC4S0UpyYYng949let9RH0t/aYmtP16J6DtD4mJn67Rp
   TMu6IBtQvJTxGlKYEPHzDSeHKLGr4EpmL2tWTV0AL0itlvXgJypJUb3QQQvJFpkAyLh8+ei
   6MhvtR0SsbffhBPnx58TVML0UMIMR4TUZvO7rKJxIgdFJqru26DTN8iE&affiliate_id=3
   487&strip_google_tagmanager=true

WAGAYWAY

   Watawat ng Pilipinas

   wagwag, wasiwas
   wagayway
   to wave about, unfurl, display

   Iwagayway mo ang bandila.
   Wave the flag.

   Iwagayway mo ang bandila ng Pilipinas.
   Wave the flag of the Philippines

   wumagayway
   to flutter

   Wumagayway ang bandilang puti.
   The white flag fluttered.

   Iwinawagayway nila ang kanilang mga kamay.
   They are waving their hands about.

   In May 2008, a Wagayway Festival was held in the town of Imus in Cavite
   province  to commemorate the victory of the Battle of Alapan, which
   paved way for the establishment of the first Philippine Republic. The
   Philippine Flag was first unfurled on May 28, 1898.  Imus is known as
   the flag capital of the Philippines.
